---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jellyseer
  annotations:
    # external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN}
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: external
  rules:
    - host: jellyseer.${SECRET_DOMAIN}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: media-pvr-ext
                port:
                  number: 5055
