---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - external-services
  - ingress-nginx
  - oauth2-proxy
  - opnsense
  # - echo-server
  # - error-pages
  # - external-dns
