# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: glauth
# Create passbcrypt:
#   "https://gchq.github.io/CyberChef/#recipe=Bcrypt(12)To_Hex('None',0)"
# or
#   htpasswd -bnBC 10 "" YOUR_PASSWORD | tr -d ':\n' | od -A n -t x1 | sed 's/ *//g' | tr -d '\n'
stringData:
    #ENC[AES256_GCM,data:BmKieGetQVFCzm4g9Q0KW4ASGUGxlsNxQjON,iv:z6AhIZq2GiDzON0QaeCtjokmOF2vALTe2NMcwc2vbEM=,tag:DPJGLgB8xb5d79WNDFAsNw==,type:comment]
    #ENC[AES256_GCM,data:18C748pZTNkP0NLBuvIHNl7g5Pcc,iv:Ap6g9yAAgHRjb/u+s0me7tsxA7wVxp46NY23nfCoE9A=,tag:Egh8ENtbj9BVRsdXu0Aucw==,type:comment]
    server.toml: ENC[AES256_GCM,data:TJ7/erUpbc4L1D/ZfvHA2Fgc7pX8Dn8MNLYKoUHG/MrdH2r9EibBCWuD8yDz53UjGyFpbsfrOWbh3g0FCFfcomYtBHs4ViRwWnQVhoSVd7lCbamn9w6Cob4kGlBeWeRQtCdUgxdtx1nKjmJy7lHf+q9gRgwToiLNpa1DztiZQwn+qomiMSX6vvyZMUdsErDzJ+z8rZVUy88NDMATaTBwN5oAzYT3PzbLGCcEdFGmh1Kjiy5VxVlvH++IetK5i9Xq5L7UuC25lWtod797xfMtD5R/ouDeKnTxDm05lLtAKdLdICI=,iv:joBSOFfvJZ8wA9EA2eWACX7CnTgj3WuM9irJ+boe2Kk=,tag:ebnshxE7yR0iLH6Ntb78yg==,type:str]
    groups.toml: ENC[AES256_GCM,data:pgjsPn3MfvhT7mWxoYGPYJXdFKeLvoQnOIMiFtCTCPmUw9ZmHgBPYHLy4AhpSSOXvBaDx3Vm5j6vbK9wfsyAU+bNcqX25gid4r7LvGttgPxvA7VEvfjDEuwCDQfonwR3F0IWwYdli42pTISHhtenYD/0NGPhTvFgXQw2WwPWQuJkKu4drg+hTlk5SoDbsswWtC+Lc/V6MzLspOEzYw==,iv:kTf2nbh7hij9N3xwgAR3iSyah1fNAuB9LIpeiiCviuw=,tag:8y6umadce/PZwt7sewKG3g==,type:str]
    users.toml: ENC[AES256_GCM,data:oe9H6orcyZihpUAqxlnDJXWvLtOPM4uelZWR4vQVAxXInSwCBo+kuO8Ccmnx6ZfooGNtxM7qnRH9WAlp292ej5StRw8XGnAWDwWdj+2CJh/ZlLb3d3VDU7UkW7fCVEP7AuMNbwuTaPnh+WXYEkpcyBWzf0dRKx0fh8oaLoIMRQnmUIWH+AVvvDQTlMMvyRR3NxFvcVWtYK2mBAgg3mpMKxkyzaBkXxP5Ap6pCNUBkmhnoew8kbm1p7uWeD2DjXkEzJp6M0kgH57779Xk/h3uK0vvuTgioFcFCOJR1xARyPRBKfqSh+SQft6TWjtavsR3q3dTatLj/BQc0cwUxEp+C2Gml8nU/IPOyA+hgGeg56VCeqHyZN8KEi2YeThQBmSKoPFKVjWNQe+JZaozXJMiSWPGtEfvAm9yElUT03Eh5IAWQSUAPUmUqMaQ3fARlsEI8wX+uPhavur05qedeiTHOd9UX5mbs6e5UnX8N5HgFTR2hIiZV7XKPhAfd2rpXEBJOwOZaR9tnG4POpynOpDangfGrWYYIj74HEy+yZDxwxa1ZUBIiFJ1f8yo/UeecD0nuA39ec77/B+Y/+FJhpd4IR6nzjlIu6LZf6f5jchMt8wMc2o3EmjsszEHZ/IEUxX8DIkwLlrQS+B1diyp9Ia4z8a+t2ii+hdbMe8Lfmem0/CT4m0KTpsVtpWI/GxRMw/HYnPwfoGAMGSuDgcXT5cI6OcwLxEX6gAqcwnkQRGU+hdAycUHtndxrECsjfLFY2YZduKWLvp+2abCGFmMwW72RqtNDm6JH5QBNjJvRqgvV9mhdSdQZDPT/xb5f2fYjYQLPS9VOCwADrM6dJHQNWlH3q7mLOiiCbZm9LLjVpdcL4UbgHVIctvKr2z+w0fw7tUPAcOTSGdBGJsBmKvOXJ7k7ZKVmuTz4vLAVetHMQK9lSN5tjF25St9frErpMPrXz8//0Y/Tc0kNSW9UHWx+NZWXAulp11tKBWju5qX6okdvy6OJyu0EnUwW8dizXXukeQVF6zlCHHH17nhrtJVivJlfg==,iv:1S/x7ORwd7KyjvxGWc4RP6I+Soh6nYaH7fu3s0GoXww=,tag:KkOFzLQLJO6Fj0yTzzbPow==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuK0psTEFTNjJBMXR3M0VM
            TGR0dEVUdDZLSFRDMm5raGZQc0J1OUQ0K0dFClJ0RWl3YUVLZ2F1YTRVbFNEdTM1
            ZUNvRWVuMG94ak0yaWIvNTYwS2FLYTgKLS0tIGNsQmJnSks2Tm13YWJTeUY2U1Iv
            aGUvdS9YV09yaXBhNk1STjdoaENlWk0Kl8k5WYd8aTYVwZIoP8kmBzSV/285yQQa
            D6uHcPgmrkTWicahJaEgp4WRSA0S4BacBvZNrMPa29oFvDKv28kl9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-06T06:48:49Z"
    mac: ENC[AES256_GCM,data:QMuqRSAnzzCNhq/fPdZ8h044Cx3sZGiuezk33nGTzHFRxcd5Pi1AkBcjzunk6OUYSXivG5qZKHjoqpH6MPb/2SXDFvdFLTvIGLVjXuR2xRCunBdo+2+BOj5ejVnmw8AdSDE7lAh5FTPJuG8cjuxGHKgCE1KYFtMmrNEBBM5oRhc=,iv:gUYY8ZEnbMQQs/oVuJdBg3Tq7rvuAQxdMz0KQEwW4hk=,tag:ViXLUZboe9b7T2ByWSRqxw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
