apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:iRNUYpvjKbW5jD7OZ+fk9B6gD8PVcZK6jPfxj4gF6hU=,iv:/1vQPiqidS3uGkPCY1r23gNfCe85xrtgln1NNJ8nPyM=,tag:u1GMO3dX9nXySNchTFFp8g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qqz7ryljcrncf70a6n0yqptdq34nte99uj8j6ppucw94npccad0q304pkw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUQkcwdXhjWUUySm5rN3pT
            ak1Kdlhqd2J1VzNjeVFJWkVuZmtza2xWRldrClp0cVNlU2orOGZ1NDBRdy9xaGNG
            eGhHbWd5M2RrTHlkOTMwdDA3a1h4M0kKLS0tIDBZaHAwclJ4bTV0QUxVRWVMaDFR
            YkE2MS8rRXo5Tm9mWHVYanMvV1V4SEEKcwv+VbEISU/7mAygt7dIDtC7OJ8kb1ak
            LE4A/P3+2zF64lV66haL1NjGSGSdqhf4PP/MpNPtXecbDl0I6PLKMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-04T15:35:26Z"
    mac: ENC[AES256_GCM,data:WVsvSS250tWT/pghGxf2gz8jBTNg4ICH9bdKCq4gfzw4V3aeX4vGpAbRJINxO3Y8TOEppXpXi9LXk89PIAr/flPKQYKGv40gLoTxLJXc+qXbTtFNH8B7Vgqmqcs5hvCVGEYHukhD1t4Vz2qBNsIhfS5FE0X3FuBmzsVyXt1ZDOk=,iv:rgRaHfHONaxo9krn3rzTxvQy3uFzP/RgYzE/0O8n1Tg=,tag:8ZX3uhWn1LKXjTFsOSFqPg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
