---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  ANSIBLE_DIR: "{{.ROOT_DIR}}/ansible"
  KUBERNETES_DIR: "{{.ROOT_DIR}}/kubernetes"

env:
  KUBECONFIG: "{{.KUBERNETES_DIR}}/kubernetes/main/kubeconfig:{{.KUBERNETES_DIR}}/kubernetes/storage/kubeconfig"
  SOPS_AGE_KEY_FILE: "{{.ROOT_DIR}}/age.key"

includes:
  ansible: .taskfiles/Ansible/Taskfile.yaml
  bootstrap: .taskfiles/Bootstrap/Taskfile.yaml
  external-secrets: .taskfiles/ExternalSecrets/Taskfile.yaml
  flux: .taskfiles/Flux/Taskfile.yaml
  kubernetes:
    aliases: ["k8s"]
    taskfile: .taskfiles/Kubernetes/Taskfile.yaml
  repository:
    aliases: ["repo"]
    taskfile: .taskfiles/Repository/Taskfile.yaml
  rook: .taskfiles/Rook/Taskfile.yaml
  talos: .taskfiles/Talos/Taskfile.yaml
  sops: .taskfiles/Sops/Taskfile.yaml
  workstation: .taskfiles/Workstation/Taskfile.yaml
  user:
    taskfile: .taskfiles/User
    optional: true
  volsync: .taskfiles/VolSync/Taskfile.yaml

tasks:

  default:
    silent: true
    cmd: task -l
