---
version: "3"

vars:
  KUBERNETES_DIR: "{{.ROOT_DIR}}/kubernetes"
  TERRAFORM_DIR: "{{.ROOT_DIR}}/infrastructure/terraform"
  PYTHON_BIN: python3
  PIP_REQUIREMENTS_FILE: "{{.ROOT_DIR}}/requirements.txt"
env:
  KUBECONFIG: "{{.KUBECONFIG_FILE}}"
  PYTHONDONTWRITEBYTECODE: "1"
  SOPS_AGE_KEY_FILE: "{{.AGE_FILE}}"
  VIRTUAL_ENV: "{{.ROOT_DIR}}/.venv"

includes:
  flux:
    dir: .taskfiles/flux
    taskfile: .taskfiles/flux
  k8s:
    taskfile: .taskfiles/k8s
    dir: .taskfiles/k8s
  externalsecrets:
    taskfile: .taskfiles/externalsecrets
    dir: .taskfiles/externalsecrets
  postgres:
    taskfile: ".taskfiles/postgres"
    dir: .taskfiles/postgres
  rook:
    taskfile: ".taskfiles/rook"
    dir: .taskfiles/rook
  sops:
    taskfile: ".taskfiles/sops"
    dir: .taskfiles/sops
  talos:
    taskfile: ".taskfiles/talos"
    #dir: .taskfiles/talos
  tal:
    taskfile: ".taskfiles/Talos"
  volsync:
    taskfile: ".taskfiles/volsync"
    dir: .taskfiles/volsync
  workstation:
    taskfile: ".taskfiles/workstation"
  user:
    taskfile: .taskfiles/User
    optional: true
tasks:
  default:
    silent: true
    cmds:
      - task -l
