# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:eqS5i7Ne8iKl2SNyMhj9pED5,iv:29H5vUwgb3UBSU4Ogx5xtuTFIckJlHmUJpoQyrcV0ds=,tag:IhC2gI7vpNznemX6uG72lA==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:Lt90htMDxNg8JZC+1Lpj+Ehwq5Od46eGVDs6d+tbJhpAyHrb3w==,iv:QrIWBEA8TyKfiXdZAZVqprXb8++pDUuHfOXphsTb2S0=,tag:lYue9Wr4e/HDXU69Xebh/Q==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:6uyzfcbhdZ6/NHBLNSb4G0XZcw==,iv:cF7ippDsQ8rtUYXgtkHz0A6IivMneQOrxkGu0Tn64e4=,tag:1+zD4zzImXsXBwMQwAOUxg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvelBpOEtzNk5aREdNcmxR
            cFdNTEZWVWdBUWpuTVRmb2EvcXFIOWJTK244CmJkZlFCdC9zdE10RXE2RnlHTUdR
            OHdtZEtFZDVuenE5MzNkL2lKaC9iRXcKLS0tIEhSdWJqdzgxOWwvM05KcUlmL1Nz
            WE04V05vVWZvc3FGR0pzNnowSCt2eHMKLU8nU68+rbEuEA6ti48k26NXu8g0317b
            g3GytaorK/EElgoxF7ei5vuMep3SRv3sMqLDOhWrF42VP6rpRKBqFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-20T10:48:59Z"
    mac: ENC[AES256_GCM,data:9zkMfFdudl5V4LMt6rv51kz1sckNRSPSZWYQ8vwyjewtya9Gj4Ip1r48bYaGRcc89tNSA3wJYBQoE7qx4KDRf7X3/q9hRT9j9S+MJm9dUxBmWocDms2EO7U3OhgAx7o+b3fyH2VBKVkZqDnGvXj43Z5TRtpowH5dndPW2humWQU=,iv:dTGxxv1uoJNttEOtqBG4X71P1qXE2BWfKdJg77+UxtM=,tag:hbsRaSAhEg8urODCrIxUHA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
