# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:gtLZSC59A9elnenRzQ2PHJDm,iv:18XqmKYEVpIELPO3Bf4xgiT+c4n2EjRZPxqf4z63A2g=,tag:LT+Z4iunMBVbalGaVPynlA==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:JtoUv3R4b0sTJQOJ/KZ9TH3UxBwDmI8LrcyyhNsnYpf+832tUQ==,iv:FqKCBIlLOeojbMKhSbLIpt0d6AeUbZrkN/Ph2uxxpJ4=,tag:Tk7fMC5dlD0O2AbLF29xRw==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:pbLX/Cs10NWSzIFAwCO7yvD6Bw==,iv:glwHd7M19yi4ps3gtvvKC9YY/d0z0loNgmFuX4IWL3I=,tag:EQEr31Sod+zB/qgmcRjT5g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVK3dtMm93NkNLTVMycEpM
            RFRncVBqT0IzMHNzQnkyTUxyNnBSSVdNbkdjCnpocTNobG5OZzdWdHZGTEhPL3B6
            TTBlTFFqMGZybmsxcW8vZVZETFgzdWsKLS0tIHJ3T3N5a0VQazBnTEZVMjVJMTN1
            eVBFcGhHOHdhYlhHc0Nnd3l0QVlTR1EKnnst68sbjvOMMIU25f7wp+3yPTsx0PXJ
            WFjUxSai94FV2tkoMCzuuQKLpLzg7CIevWXtULRd2Aovj/je+/5cuw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-17T04:15:18Z"
    mac: ENC[AES256_GCM,data:hJ39MnHy2JhFvXShZ6tmcDwnnZfIi8ATc4VpmHcpj6k4BjVSykoVLpxUBrF3njKIbNYM6tzc4ATk60Fue8CbHjnxB80foo+taw7ESmbOktBgz5eV0QMrKZl+srz+aj7Eqme6GbEafxIImllpF9DDvldzcUEHV80gq91z4MyoQls=,iv:uP6tJnxMDe1tioBsXDlud/cSC9eKC1WjijCJvorcA3s=,tag:B2JEgzFkhOZTHsiAk6TXuQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
