# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:hV+f0ESH6/nneekVwh8ATT6Z,iv:LjLCtv2BbPWhiffAy3eSWlUp6EC4gvZtjlZlINg7RAw=,tag:WIOVVA67I9xpAw5TkpQx2Q==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:zY+hcuyu+WuvPVrSaZQadT0Fv9nxd/OeGgJDg5oZ3yQhbGbrJg==,iv:diT3EFjK277R5IJb5ILey7JctWLhNyArT4RpAWCYJ2g=,tag:Z8fw9KRwoVgQ352QcRFMGQ==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:Jsmcz4GiKJNzObZnELiLOKJnIA==,iv:xe8fnB0tP/A2FK/ADgT0mSolXgOVPGmWaICsbgulEvQ=,tag:eRqgsAgOHzIC74BHyVBujg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxTHMzbHFrNGxFdkFNY1ZJ
            QkU0S0dNblNGVVk0alZiSVNMbjg0aGNDNW1zCjdQc2s2Z1J6cjhhQmtDamhIMlFT
            OW1pVlBPeGYvSXlTRlY2cy96ckFyazAKLS0tIDA1Vm9zUkI2YzNuNXNIMGIzQjVW
            TUhCanBuVldxb1pqNlgrUGhSUTVWdmsKIlI0H2r+V73m+GlvL2JVhc8/XXnZOc1t
            juGczFcqf5o62aGO1ml+EbINCW3ij9yr90/436HtKfiSmNv8zZG6UA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-17T03:57:05Z"
    mac: ENC[AES256_GCM,data:cVLoCKSRFWakDA/Alc0LOPk2oGWLtIZeCjSk/D3WPTVpkGAE7hoHaL1Mcssi+u3mXc/+hYoyo9yQOXa0i4zVdC6PINwk1xa+uzHc2jY7+T774tiZA58a5hFZ8qBIxB3IhnSRhdUskyyW8LXRMk7NnB5zH75Vu7TjcP2q8wXRDAk=,iv:otzt40XPG7JoGMMFyrGCvM5Fou8lSmU17ORbqhR7/SI=,tag:dqkl0it6Cv/02PCk3/IU+Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
