---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: octoprint-data
  namespace: home-automation
  labels:
    k10.kasten.io/backup: "false"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: pve110-dynamic-nfs
