---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: octoprint
  namespace: home-automation
spec:
  interval: 10m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: octoprint
      version: 6.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    image:
      # -- image repository
      repository: octoprint/octoprint
      # -- image tag
      tag: 1.7.3
      # -- image pull policy
      pullPolicy: IfNotPresent

    # -- environment variables.
    # @default -- See below
    env:
      # -- Set the container timezone
      TZ: "${TIMEZONE}"
      # -- Enable MJPG Streamer
      # Enable this to ensure camera streaming is enabled you add a video device.
      ENABLE_MJPG_STREAMER: "true"
      # -- MJPG Streamer input parameters
      MJPG_STREAMER_INPUT: " --fps 30 -r 1280x720 -y "
      # -- MJPG Streamer camera device
      CAMERA_DEV: /dev/video1
      # Set octprint port 5000 https://github.com/OctoPrint/octoprint-docker/issues/160
      # OCTPRINT_PORT: 5000

    # -- Configures service settings for the chart.
    # @default -- See values.yaml


    # set enableServiceLinks: false https://github.com/OctoPrint/octoprint-docker/issues/160
    # enableServiceLinks: false
    service:
      main:
        # -- Override the name suffix that is used for this service
        # https://github.com/OctoPrint/octoprint-docker/issues/160
        nameOverride: svc
        ports:
          http:
            port: 80
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          external-dns.alpha.kubernetes.io/target: ${SECRET_DOMAIN}
          cert-manager.io/cluster-issuer: letsencrypt-production
          # nginx.ingress.kubernetes.io/auth-url: https://auth.${DOMAIN}/oauth2/auth
          # nginx.ingress.kubernetes.io/auth-signin: https://auth.${DOMAIN}/oauth2/start
          hajimari.io/enable: "true"
          hajimari.io/icon: printer
        hosts:
          - host: op.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - op.${SECRET_DOMAIN}
            secretName: octoprint-tls
    securityContext:
      # -- (bool) Privileged securityContext may be required if USB devics are accessed directly through the host machine
      privileged: true

    # -- Configure persistence settings for the chart under this key.
    # @default -- See values.yaml
    persistence:
      data:
        enabled: true
        # ountPath: /octoprint
        existingClaim: octoprint-data
      # -- Configure a hostPathMount to mount a USB device in the container.
      # @default -- See values.yaml
      printer:
        enabled: enable
        type: hostPath
        hostPath: /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0
        mountPath: /dev/ttyUSB0
      webcam0:
        enabled: enable
        type: hostPath
        hostPath: /dev/v4l/by-id/usb-SunplusIT_Inc_HD_WebCam-video-index0
        mountPath: /dev/video0
      webcam1:
        enabled: enable
        type: hostPath
        hostPath: /dev/v4l/by-id/usb-Verbatim_1080p_AF_Webcam_Verbatim_1080p_AF_Webcam_20211012001-video-index0
        mountPath: /dev/video1
      webcam2:
        enabled: enable
        type: hostPath
        hostPath: /dev/v4l/by-id/usb-Verbatim_1080p_AF_Webcam_Verbatim_1080p_AF_Webcam_20211012001-video-index1
        mountPath: /dev/video2
      webcam3:
        enabled: enable
        type: hostPath
        hostPath: /dev/v4l/by-id/usb-Verbatim_1080p_AF_Webcam_Verbatim_1080p_AF_Webcam_20211012001-video-index2
        mountPath: /dev/video3

  #   image:
  #     repository: octoprint/octoprint
  #     tag: 1.6.1
  #   env:
  #     TZ: "${TIMEZONE}"
  #     ENABLE_MJPG_STREAMER: "false"
  #     # -- MJPG Streamer input parameters
  #     MJPG_STREAMER_INPUT: "-y -n -r 640x480"
  #     # -- MJPG Streamer camera device
  #     CAMERA_DEV: /dev/video0
  #   service:
  #     main:
  #       ports:
  #         http:
  #           port: 80

  # # -- Configure a hostPathMount to mount a USB device in the container.
  # # @default -- See values.yaml
  #   printer:
  #     enabled: false
  #     type: hostPath
  #     hostPath: /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0
  #     mountPath: /dev/ttyUSB0

      # usb:
      #   enabled: true
      #   type: hostPath
      #   hostPath: /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0
      #   mountPath: /dev/ttyUSB0
    # securityContext:
    #   privileged: true
    tolerations:
      - key: "restricted-node"
        operator: "Equal"
        value: "octoprint-server"
        effect: "NoSchedule"
    # affinity:
    #   nodeAffinity:
    #     requiredDuringSchedulingIgnoredDuringExecution:
    #       nodeSelectorTerms:
    #         - matchExpressions:
    #             - key: feature.node.kubernetes.io/custom-CR-10-V2
    #               operator: In
    #               values: ["true"]
    resources:
      requests:
        cpu: 200m
        memory: 200Mi
      limits:
        cpu: 500m
        memory: 200Mi
