# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: k10-dr-secret
    namespace: kasten-io
stringData:
    key: ENC[AES256_GCM,data:Zmd/WfZ/LR6g6LrwHquYFWnOSad/SjYfiw==,iv:xXiNfHPvksB9UUqDX7oj+M04vEbTghvjQQyu0e4doR8=,tag:KCp92/Pd2IQiHTui4wUbsg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzc3VUMmJEWnZncnpodHg1
            MDJJNmFsN2ZSa1dBclRVOG1DS0pTQXcrSFFRCm5NSjFQWHYxSnR2dHpkM1pBZFhr
            eWt3NmRZWE0wUDdIY0NmMktEM1QrS2sKLS0tIDdCUUR2dkU5UVB4KzN1QWl6WXVT
            bTE3SzE1U2dLYThUNytjNjFmS1o2S2MKDhWNy/4uTTQPbEn7x2lfrSCg+dSRDXP5
            PqyIb6pdYqPFHguuTyHSAMjmsvcL/r0+oQPlIUnoHZ7wZeBUKJMd5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-10T09:33:48Z"
    mac: ENC[AES256_GCM,data:4iFVvW5YcMhJh8nMAr6YjnXXptIK0Y332RP55Kkc1ikP1CaLF5Cu7m+68zRJyxeodK2jCavFmVQGNQn+7GVA8UTwheRLuk6NHs/0u+xdcteeBaShPNEvRphubbfS5Z2RVK2RQ8DA5ZqcqiN6lZnNUcD0NirysQJT41ZmBcd8Rjk=,iv:km4qkFj5pXOF8OY87oKkX/4AA4wfJTQShDSFUXCkFIw=,tag:PsGuW0BvWJfjs0CtCkFHsw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
