apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:sownX8xepzT4zdt2KdF4ywsjopryCXQ6NRtYjbCk74JC5nR/CskBOw==,iv:HZe87tDnb9miI/tr1tMh0ZNLxqdKf8LwihCI3BPE6P8=,tag:COX+vWKWCAKZ7XWBBkpfkQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3bjBJVmptcnNFM3FwbnAz
        b2RTWTVrSytVSE1sbXdsRzkzcTJCK05VR1FnCmk4VGV2WEtZZkkwd1ZBa3ZxSVdY
        QzA1Y2paZ2V0Ti9ZdE82WFV4VFRGbnMKLS0tIG9RcndaRVVaNW42Y2xsdk5SV3lK
        ZjhwNHF0NUNsL0srL0dEc0RuZ3F3ajQKeNvLLMUcuWpUmy8o65Y3IignSmqScW2F
        fnZfKMeXrhHIIOrVzZd+kMcQOaS5GsIZoNN/xwcqhgaFQkwG3vS1ZA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-23T15:18:03Z"
  mac: ENC[AES256_GCM,data:sNYzim5eVi3DIWx2g0+ILWcR2jMzU3IG4B4DK72JT8imL0nN0f3VVO99y+tMtTj6yUkzBYVRcpPmZmoo07J4AK0W+xbY83i/lo7JixO6rnPdJIJO1Zimz1srEu6Hg1sNI1xgMzrNi34KWRiYiTpnlvZe6CqTyQhf/AsRp6f62fk=,iv:YDqQDev1sODjgtQDC6HFnv0k0iXcgIdW1mg8b95hx2k=,tag:aZUi/eXdy+FgEGx7/YJsJg==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
