apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:BZTmVn+nELSx3vXuhhBUI1YLTsVGSbd6O47LVMvA57DuzF2mq19hiA==,iv:1N9VlVAtOJ2+qWpZZAiwJNVPJDvpARnW+gx1Lx49R0Y=,tag:6K/z6gNRRWuS5zEMeeNkrw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDZk0yYmFkek91K2J6dnIr
        Q2N6cnpZUWVyWmlhSHZDeHNKL2Y4cGlQR1FFCkovSzltTE5SQk1xU2s1SG55SG5k
        YkV6WlNKekgvWHUrMGp1VWY4L1gvTlUKLS0tIDhpMHZpWjdqelh4Q3k4dFdwTUh1
        VEg1MXluT2xiMTdOb1lPN3JCK3hVOUkKXivNAYncHFSzQBT1kOqbNzCdn+mhpCdH
        VEFVBaPi60Z9Vcn+i5AwfSybLzPBuCruOFuHvm0JXbSVdeG4xd6mdw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-24T00:49:36Z"
  mac: ENC[AES256_GCM,data:i0kQDjghxuWvF3qwaQJFzFud3GMTuVwVsMJTGqSdZby+5V4SntHxTQdjq0aePABdR2Kql2g3fEM9v9l1OcFnVpaPngye5Pjyi1HK5H8xtU3i7afze7bzOTC/EcsC7zE6o5ZVbHvvzl7nlLRYVMHhJDdSgfAjyK8MkH2Aqf9r1gA=,iv:2uEaRif8KBS+/Lf1049yoexQB+R8lAkvcAbIUYJprpY=,tag:/fKCcDovGfaqsCfQIADAYw==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
