apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:RZVI06iSTcruDaWllf/s/SnGza2/R+mzGMPuiuh7fOShr5a3I3XBiA==,iv:NbUr97T3gUq28Wm7TMKKQo1ZtS38Im25P4Grf2HHxPo=,tag:5t4KGd3ax+tOKJz24I5eZQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOVHFlSWZZQ3J3NU1rMTBj
        ZTd4ZXhsRUQ4bG9HWExpZk5DQnNmbTRiY1hrCkdMQU54VytUNS9Cei9EZnVTV2tq
        M3ZHS01oaEd6TEg3NHdqK0Z3Sk1vYjAKLS0tIDYzU3Jvd2dtWkhtOUpJUVJQV1gy
        dzBzYmc2NXJnazl2Z2k0cjRGYnZiaG8KeFhMPR7e5yGgKDe54ReVU3H5//8/NRm+
        bo61cb874m75TfEH99vuuM8rAR17gSlt1A0VBUrVYtjOjS0Sh4SNjA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-23T10:34:29Z"
  mac: ENC[AES256_GCM,data:/yDg6bBkrZjOw/ru8/XO58gW1+aC35Sd9bLTFCqATtiTpsR19wq4Fq6fuuggQ8DZ72uEYCD6aIbWSbeWGS2nq34VwcSeAW0P5YU+f2gZimypslWSHZMl6YV+3d/mDmifpwQneSzJEf7AQm+SdBlvoE7UweOjFje4eN21860ftMc=,iv:o+HnDRoZhYKANtBhcXsF146SApl11U60aL4QcOi/+54=,tag:v5q6ebYn0lib91oWtym6XQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
