# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: home-assistant
    namespace: home-automation
stringData:
    HASS_DARKSKY_API_KEY: ""
    HASS_ECOBEE_API_KEY: ""
    HASS_ELEVATION: ENC[AES256_GCM,data:HDdy,iv:pyHePglKKnRQJ/IVVfqIC7PdNMgwgdJZ/ROmRukXlaY=,tag:0DcBGOJtbbTKml+ex7PxCw==,type:str]
    HASS_GOOGLE_PROJECT_ID: ""
    HASS_GOOGLE_SECURE_DEVICES_PIN: ""
    HASS_LATITUDE: ENC[AES256_GCM,data:U+1+fj1kMisvkA==,iv:PtJUzzbqcw93pMQbkWDj29eDFOo0KRxV75e2KnyRxdM=,tag:CxZiXybJCSlSKSkdBRPApg==,type:str]
    HASS_LONGITUDE: ENC[AES256_GCM,data:p0dw8kM4xbQSlQ==,iv:e+YoK7gIk5PizGfRfMW8ZDIACpHD2nR7xHjUwYGp52M=,tag:PxCa5XdgCupewwNL1zriJQ==,type:str]
    HASS_MQTT_PASSWORD: ENC[AES256_GCM,data:p9wqf/ubPjyq4SHRLKxS5HcF//vgbOc=,iv:SBLiRjYhfuGsISGWlO4BB4O1cwvjlRwm2LhqMcbhPzc=,tag:xmdfmS0hb1aHyaOabmqcUQ==,type:str]
    HASS_MQTT_USERNAME: ENC[AES256_GCM,data:QfL4tXGDrF/tICADj3bOaxPBWnS4bn8=,iv:aqEmiudy7Y9X39FkR0ufkEwL1PW/vGDs85W1v9kxp5s=,tag:SRTmRijIumseAHvrFJ/+KQ==,type:str]
    HASS_MQTT_BROKER: ENC[AES256_GCM,data:tlsJ4FYHkY+n6LG3Cl2GPTU50CM+iOkL4R97pSwhexM9+VG6aGU=,iv:bGc0Fv6wmoqXcwFy8yjcto5y4iQun9hZJgsXLTZ2flY=,tag:uykbmfr2i2IaN02OaCjazw==,type:str]
    HASS_MQTT_PORT: ENC[AES256_GCM,data:6KI5ug==,iv:AjGRpHogGsJmtuIqZQAdxYzLMBLCOkq5ONqy2f95wYc=,tag:DBvEHYsBAs6IwXQV40N+Sg==,type:str]
    HASS_POSTGRESQL_CONNECTION_STRING: ""
    HASS_SERVER: ENC[AES256_GCM,data:mFXDAOiN2h77Eba8vSVMsgkcaQjT,iv:OkweAJxQ05DsTOu78gK964BeTQGjz40OqMZyke8p75I=,tag:BKFGk1gSrX2qRw712VbEiQ==,type:str]
    HASS_TOKEN: ENC[AES256_GCM,data:MWGoiaWzU6vGKPsV12dT5ySOjk6yDy3ShZsLbqBbuF+LpYvKLT5ChoEftv0r17wUMYoO2Q4o5VvsQ2/tack2FVH52Yc0uhyTl17o9eBMPf1HnkAb1B8rpJ3Jc23m4WvpIniYPoCQ89uDXNQQiF5p6RrljcyMzrAUJpNR52tjAWYiX60dKQttiCFdgEdglKYRKNVxjdA9n5R7GVx7ZI+s/Xm6DQdwtUkzqwrcpGn7jtreTQ5ZtfeS,iv:iBnw2WF9yzIilnLJPe4g7gzJuQwIf2IwTWSl2HOyPZs=,tag:/EX3vdQXJucQ4Po418QGDA==,type:str]
    HASS_RADAR_API_KEY: ENC[AES256_GCM,data:IlOz7lMY+I/DxuZ61p/2BSdLVmvXcPsUM3AFYdoobt8=,iv:QvCISkXsQwp6yq31a9IgB0G8yNjMXaEUo34/DWWHi7Q=,tag:jCJbNdRXaU9j1cGac+cRsQ==,type:str]
    HASS_SONARR_API_KEY: ENC[AES256_GCM,data:docBf808zNOaIH57vNxNbQ5yvkD8rfF1c9j8rjiU8vw=,iv:ArCJlPEqpsS0K5F20WzklCwMxCHhFT2muta53bENOVg=,tag:ujZKZgMiNZWRC9U74hUGyw==,type:str]
    HASS_SABNZBD_API_KEY: ENC[AES256_GCM,data:87g0Xqmsg163sn+Nj4NUFjSagzUCB/4WbXOZAspp/Kk=,iv:AYR3YBXqr8fSfaHKgs7cn4ANRnlPzIW1tDDUNlw45QM=,tag:GBaW+OLZAnHkRCtpEaHAww==,type:str]
    HASS_OPNSENSE_API_USERNAME: ENC[AES256_GCM,data:jphQ5sA5N+Q1MwDZayhQ0BB0jKJp79tClglSQyFQUGgMdtIQBHu24aqg+MAP6GAibcmgCiVl1cQXJI/FtAFFpMVdslDbwCaDKajI59HBpu0=,iv:KM7Q18EW4YQ+D7ssX7NYoqrn2rkyPl2L+EWhoAb6f0A=,tag:Kh8cDYfXNCoxAjnoo6BweA==,type:str]
    HASS_OPNSENSE_API_PASSWORD: ENC[AES256_GCM,data:06vGv75daUEy4qd/HdUW2nSsxtvq/t1ifdmgmxiB6AqClDBT/euKXsN9cXSW6yEl3xOetl4jEDirhMrgM2sLFbVH3dgPlnaMCHHADZsnDiQ=,iv:QvJru1iX/qZsj+smIP7tyIENdldOqcTl2KJqB193fZI=,tag:9Y58akN61QtsiY48KxySPg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5Sm5WKzFCSi9yNlNJNTFQ
            Nnl4TGV0dnMvV2dzYTdDZUR3QjQrMWtsNGwwCktpWEdWUlN1TXJrellFZXN1TXhU
            ZkkzelRpdlJOZDhncEFYYXJONC9Jb0kKLS0tIEc3b1FUQ3VqRGdRVG05bGdocFFT
            VmJhQm5tcUFnOHZFQU1JVDg1aWZxSU0KC2sptqNHma7vTKoxBLjtPoUWHOzZzQLk
            4ii0jTUR7Hk4ZHBZXo/6ksFypXmENIbriduelpQ3KgPT1H+FiCWUTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-21T12:16:12Z"
    mac: ENC[AES256_GCM,data:tedE/qpX0KhMTiRkJLoENsftjhXqGSbEyGkMVRR2mY76+RC3utCUAl1+/FRu4ECuzhabGpoLEbA2mnddciMtKXJsQEpX++oikfftUo3qI5l5r9RLAutXIYZxuPJwhbKnCeZq1KrfW1b8Cr/6J5TUBe6q+qwyBG6OhZViS7N2TOY=,iv:PoLrbvWgzFzFg5jtmt4G6d1MI9A3odClV04d/7dScnE=,tag:JalQEg6W+2/aEe+7XQwVwg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
