# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-url
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:F7e3mI5zjZT1Wc28mZKvkW5B3aZijqO7I1yj6IqVo5eAEb3Qo5fPVx5EjLbkKnkUS/m4pHQ1wMqr3JPL+D8GW9d7EEGHik0CF9uywuMDbv0RYBxseQPrgsaH38pdgCmfmcOosRxXujflweloAZ74JPUyW6YsKxQ2,iv:YYAncrBZiXK9ciNRsn2mkbu0M4/mYiA8870t5b62R2U=,tag:2Jq0irulJXMCqMOvdX2qzA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArWkNPdTU5OGIrRllUYkQ3
            My9WMVVDVG9uVlJuelZuWWZFVHVWNFhaeldvCldNVXloc0Q3Z2IwZlBXL0djM1B1
            ZmE2YytvWTA0bklqRytlcmd2T1R4RXcKLS0tIE90eURBMXo5OW8wVDVRc0RMM3ph
            K25OWXNQOWtjTCszNW5XdmZwb1gwNHMKgFiJyfY2kl5whj31+fX+4QJZdx0+IpIT
            RCjFcNhzcG/DoO6/cu3fI7zie1CV80bhNcQR4Evjf6qn5TTWlSwQdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-13T09:03:05Z"
    mac: ENC[AES256_GCM,data:WX0L8YnbwnKWGyjNQg/cPhzUIy5nsiJEwnpCu5999YXlxQSf5i+ig6RyF1ZNwXAWWrixF4Ql0MdAnbMOkS85Z7h7lFN+U/xKXFYVp2bjh5BJozY4HYV8+pxCaIpd+pCq1HZp1QKf0wkk5IxmMnf6vlhMSrqzW/wmLHy5C4NVXHw=,iv:G3mNNwPVKOnu8rLK5CYhLkQJ15YZafmt1TicpFTNzpE=,tag:JNACoQFcS1yeuVAw7HuV/g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
