# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-url
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:xgj9Uv+9+yk=,iv:DYmcNmMp3v8IGUPzbgFruVzDxWe/FjxEyGp0yt6GX38=,tag:zir4X5XGjXEJe+bQyhe2ow==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6VW1QOGhkNW92UzlVMEVw
            WDlzWS92TUJtMDBBRzQ5UnpUbFl6WDFhL0hRClpEMWhwMi9zVXZSYmhrQlNicG1q
            SVcrdlpHdFA4eGNHeXcxa0tqOFIrRDQKLS0tIFlTV0hYa1ovSkRRanhGU2RWbEZK
            UnRzYnN1ZWFKczZabm1tck1GcXNPTlUKxHjtxYAkt9ptMxkLPzOFbRIjHPYNvvJ0
            ZJKiEfbH7G+iW978CRcP1eY40wBx2oeQwmM04Gmt7r3EW2ZHUID3zA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-09T08:46:35Z"
    mac: ENC[AES256_GCM,data:1vgiGQxiGZN4+/HpReRex8vWa4rompM55//+dNjLPhe0WZSzuhBBASY1OPB8HgsiFzsJZlNshbWVX2TRFS0VlgPYHabn3BORslfX4iXgxC1lL+UJvNWXxRD+AUDRI017k8arySim7I6CrsY1o8yaKD0Q6Kx0Jn/yzM0DydY0UsI=,iv:QQrUxMn4KxNaAQ1Cp1eLrUHcg+A6JnVqWgbVobeqS/U=,tag:aQm4YqYp6STYCjLQWNpk8g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
