# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-url
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:EucFX8SuO/0=,iv:ohkKEnjeeooGWZq5uj/E7s2rW+BpWLRLTb4w1/PkRKg=,tag:hhApdpcXhkGsu0lPGxQC9g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4V3FueEVWc1JmT3V6MEVI
            ZUNJZGYybmt0dDVwOHF2ZzBCRXVXRko3Z1RnCkhiMWpndXduN2ZkSFFUc1Z5QlJk
            WTg1ZTd2cWN6bHQ4Y0hmZlg0dUhoWjAKLS0tIDdPam9xdVNGeXdiVVJOdlp5aEUz
            aitVZGJUR2Q0VnozbCt0NVh0d2ZtdGsKXufAU7BZ0AUojTGJN1TFQ/its5ksugkp
            3UTzYGP8CWop3N1JUmr1QBhKAcjqcZLxTubAdVqovNZeidnjWU+4hA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-09T07:47:33Z"
    mac: ENC[AES256_GCM,data:7QHxQPjPyXDH6W6RVVDmIpfhD+qO1y0z9NUWO9/6XVdwaaorf7rcqzS1HscYce1N5EeP1YOV80vIPx4DSUrnXWT6fmOxJQdunTwn5XtC7IduyXHGYI2QUmBfoKWWN/B0xxwZu9PSJXwTSDoC3cQ0MdRQQ8jSLHOeywg/GUz+JIA=,iv:i+dwyW3yGF0dqFn6neqWZHVV1GnFPFnpLvU7VibLM6c=,tag:Y37deXcEVSXkkQO6eWdahA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
