# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-url
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:IAknMmM/2eRyc6+HU/eNqvY/s4ZdnzRXRqNxMms6vw9iif7kKbGhKANDmUPgBx3UtvRh0BFoATd6AqNzABjpOfTQj4WKYfWznhlRfSJOh4F0fud569L9jYyG2oP+J732y0kQBZxCUOJTAygfBzjk2nj2ShArJWd7,iv:2g0h5/HOLjs1zAWt/TpsnKNY9l/+oA7YTuJee1B5IVg=,tag:q2S3KEToFfiGRXFpnGBguQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqVWtHdUk4MmFHNFg2U0ht
            cHR2clRkR1NkZmVvNThpVGVaKzBuL0tLUlhZCkRXdDVyNmZoUm44YXV3ZVlSRDBn
            NXJ0aCswTVpLeHFHOFpPTEg3QkdaOFkKLS0tIG1QTzRtdURsSU1wTkVsMFFoaHhU
            QzJ3aWxxejR1TFFScjVTMklVZzFLVUkK5CvB2qxCPoSEnMbsg+cNrV/OTcl9eUxf
            UXvlYgHlIrw3OnzbUMrlQh/yRHAP7k6o8psYk306b1Fq6QO004TUKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-30T01:45:21Z"
    mac: ENC[AES256_GCM,data:/M1ta//NrqC4SGio1AqjZzvzce4Cx5iVv2REgHbOYP0x1FE4Rpj36XwiMMDC3JeSG6HfLXcOXAvJrIPJ2VKsFtKCMeRRLZ6TIKCd+Gj5UJlzo91u5tQdOuc2N1cqB7rnkp7+hFKH7KiEtpwwKBN/d11PZeW0DtWH26525xC6/Kw=,iv:6uJwTMJBaIUFC3HgsbK8zxYw2SRhet2UhQGqzeM7tqA=,tag:yYafuwD4Fqjl9aCilsvGAA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
