apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:46rOiYUr0u/Ilkw+FgQ=,iv:i25yogp9xJvjvX1i7ZCwqxK6muSmJOsQf/TvEED3Ot0=,tag:danJLOULgvgEeym7//stvw==,type:str]
    NFS_IP: ENC[AES256_GCM,data:CTJnIT01Jx3NUBg2IQ==,iv:MdLBhoo1xqgEUCY2yxWYL5OEPBCSrg78CnoU2dY++Qw=,tag:MOmFeAxpzZrtIYuA1DpgoQ==,type:str]
    SYNOLOGY_IP: ENC[AES256_GCM,data:0SrCpP1PZOZ17eUCWA==,iv:yxqav4sSrPMOa7jM+N2RgJSU5pwgJE86gl3aKjWbfAE=,tag:020t1u0alH33GfroPzE3jQ==,type:str]
    ROUTER_RNDC_KEY: ENC[AES256_GCM,data:0KM65ZWmUROAakcW2r1JK6nd+lLa3BrIykXGbf/OyFgfhlwO0GjnPAHivaaQq+5YWvecuzxpqtN8U6qCLcxAkrMcojVMnyWAKjrUcCFpbBQAnbCiJ9rNpg==,iv:AwQYy9AGp88J3OddOh6B0hOEjnpjhjXMK3ZFHwM3mpU=,tag:0tXZG1Vx9q16Arw5gf7bjg==,type:str]
    SYNOLOGY_RNDC_KEY: ENC[AES256_GCM,data:xzYiebX4waDe1pAXloOEMDhM5Lk9jN8eKuYCgoOpKioLZqH1RUy/u53yNx16BnOOHgMs7x5bYuFpv7fNcYhkgAUTimqCPGBVAtBpxPhFZi3lwLNLcMKx5w==,iv:asB6ELBqc0jV6o2MPePvptjlrXGhj4U8UZ8iA8QHMhI=,tag:di0czb6YobjhwV27B2bWuQ==,type:str]
sops:
    age:
        - recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1YlViWDRqQ3prQUN1d3Ri
            QzFaRDVPSVdDYjN1U1Z6S2ZrSURiUjg0eHhVCmhHc1loWitHYmt5RjJZQWJlVTVo
            Ujl1SnZLYjNzUFNvZHE1WDBSVlhPUFkKLS0tIDdScW84ZFkzN1E3WXFPeVNQOVhY
            ZHZJaWVCODkzMXV1TDU5ZGpxYWFMUWsK/KbHpfEalwCFarFkTtxE+FKWmBlPrJMw
            5JaZdKNb5qUZ3j0eeWLNn/30xZlNqfN8eMZAB2WtiEGm8a0OjLjcKA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-23T15:51:50Z"
    mac: ENC[AES256_GCM,data:i7kS7Qijx3TGCN/NEKsnQ0rq/3ASGQAjKWyhHI9lcMUchI6s1/OsqOXLeEas+2Gm8cZ6dE5gK60WwdTmDVbT75j3UcJySvF0qi0d0BWsEe6ZUeWNzPBdJxmAo4BUNwK+z76WOcICnOnLhdvYQpQoT4zbqegZ42xfLMpoNWzBvgU=,iv:1y9K7esw2uNcveKKl3gBP7hqmuGWZWKZ3lC0AN+3jTU=,tag:T+fgfQiA+kXa+6nxj3o1PQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.13.1
