apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:BTIunRTn/54FKaRX6c4=,iv:/tdqhLOvuJnWKh17dO4da7d6oOw541sREO29LSd/Eao=,tag:iUN7YdzTuuShCuiTdcJSnQ==,type:str]
    ROUTER_RNDC_KEY: ENC[AES256_GCM,data:gWQdYUJUAEyBECYWV6ZSD7Kgi9/lhpP32mWX3DfmzUHZtfMlLN7NHI4Srt30lTBBNF7bbQkwGRg/QzuTfvAy3F98DPC6ItCke75ClReX9fdUPfOTcBgNWw==,iv:VzRrNDfvGxX/FMTtcCppFH0KgXN1WAeYVV5O4A94DM0=,tag:6emNiLOksWoFntqaOkwH3w==,type:str]
    SYNOLOGY_RNDC_KEY: ENC[AES256_GCM,data:qdyNSVhIYm1sdQzYz5ph22/XTbEkF9OFcuZKJwKa32d71i9oQsELc5FHcXmB0zwGBFIxEKbHafqaz4oV+eKReHEQttFam3bmyvPyP+tuPXnk6e8dHXBhpQ==,iv:2QASBmwU8gfwU5BIiAI+46fY+8Lp565FVTFe2qJh5fw=,tag:IV6BZO00Ds0M3te+tKqEWA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:QcxfB36NYht9OrVea47wJXUU,iv:F6Pl3YMR1OfroLDjBu25irtOvMgP3d66bq05DsLb2rw=,tag:986mSS+ykQ2mou/yhjNOiw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:5bpcv8JCVbeMxrg4OAwxY9Fu+g4C5j/I89qlGTdZXcmVMH2C,iv:TYmyOF//pNgfy9gjNVEwoJJhW5KxT4hnavQ6/kwkBT4=,tag:/gje8LwXJ3H/d6+p6Qqwqg==,type:str]
    SECRET_PRIVATE_DOMAIN: ENC[AES256_GCM,data:4FIOXH/gRF8=,iv:nzvcfOw1+SpxArPfyw9GhzYXbV0qXo9lJH+mh+ABkJQ=,tag:5jRYuumkAazUyCALL0HXzw==,type:str]
sops:
    age:
        - recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrZkZJMHpVUWJKa2RzVTgv
            NytrYW1XUHlRRURFZWlWSTBDd3pwK0puVVRBCkhpMS9mMERNL1I3dHcrVWlqRzNL
            b0x6Qi9zMGNLazd4UVNmNDJVM1ZIdjAKLS0tIHRoZDJQWXhTZE1VcElSRFBscUZN
            UzdwTXA4TXp6V1dxQlBMK2EraGZNUXMK63qZcdSahAWZCF6kAAEZDG82ou1JlQVB
            WPyQVNWytitNd+d0ycAJXJt6qPTJ4nFwYMryqcgynMQ/kBjitkP69A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-23T11:03:04Z"
    mac: ENC[AES256_GCM,data:YSPzziqAXiEcILVVBmQF0YRm1Rf8c/tTI6emE6CLHRnRxXsaKpDDpQeK5Jx2MAcTwKx0LFjNeJCd+ZPYa8LjVhVnA6KqbXUsn8QeazII5Nnyby8ESnFOw1/6tfLDr9Gmy04prjHMELNaiIWyC+dx5/IOEKpzqqKnnwzR+fAoYME=,iv:GM3kq0pdSuqSLZi3h6NBVhAQLgXmuBCg3c1U465fbG4=,tag:JopO4dBNUt6gQGVTBr+BAw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.13.1
