apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:BTIunRTn/54FKaRX6c4=,iv:/tdqhLOvuJnWKh17dO4da7d6oOw541sREO29LSd/Eao=,tag:iUN7YdzTuuShCuiTdcJSnQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrZkZJMHpVUWJKa2RzVTgv
        NytrYW1XUHlRRURFZWlWSTBDd3pwK0puVVRBCkhpMS9mMERNL1I3dHcrVWlqRzNL
        b0x6Qi9zMGNLazd4UVNmNDJVM1ZIdjAKLS0tIHRoZDJQWXhTZE1VcElSRFBscUZN
        UzdwTXA4TXp6V1dxQlBMK2EraGZNUXMK63qZcdSahAWZCF6kAAEZDG82ou1JlQVB
        WPyQVNWytitNd+d0ycAJXJt6qPTJ4nFwYMryqcgynMQ/kBjitkP69A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-23T10:34:29Z"
  mac: ENC[AES256_GCM,data:3ZgTHkGGjzf19a/H8ElTe72shK5Jm+cXoa4U3uotFQHtLoN1JSzjw/Bkz2LHTW8BeXRBuXTDwzWeRxM1HOUjAJ4MbBy1UNXZr5mCkZENuLX8W6RRxJsDAF4gE9+l9DIpBwiNGBsV1vdx+D55UsKX2kdEKslBTeEPxT9JpdIp69I=,iv:RiGNjY+oRMqkYWYvYWo5rpWMf8qpkyuxMTMHtgqcQXY=,tag:eDE05E4q5bsvp5ClaKAV1A==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
