---
kubernetes:
  children:
    master:
      hosts:
        k3s-0:
          ansible_host: 192.168.16.100
    worker:
      hosts:
        k3s-a:
          ansible_host: 192.168.16.101
        k3s-b:
          ansible_host: 192.168.16.102
        k3s-c:
          ansible_host: 192.168.16.103
