# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:8F5u8uFCDvN3kagL3nJoVZdWCdEjewtylqC5BIWJlYsUe8jpYw==,iv:JGIN2vRNeZFgJTB+A16uvtBzi13TxV0Yf/3btOxY3dw=,tag:Sq9BrgFFkdvhH66rwzbR9g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIRXNwMUZ5bjVZMFhIckI1
            SGI2SGR1RS9jd0RvTjNHeHh0VkJsVUNNVTA4CmtZcklBaHBmcDFITGE2WEtidGFy
            ekl4RkpJSDFxU3pMeGZPcWt4U3NaTXMKLS0tIEJTM1BoeWFhMjR4ODFnRXp3WkNz
            SUxKeEkrSzk2K2FCUmVkMERrWkVWaDAKhOeWQ6M+hZmPRId1s0x9JTXC8MMUJIyN
            /v6eCDUEOFMYNsWrMN4EjTnTZBFtGsupHp3++IFJ4RnFwoX8tQ33lg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-17T14:29:22Z"
    mac: ENC[AES256_GCM,data:JwpxS0c3OFySYpRSZVs4zDZsC8TO8vTgf6CcmPtxk5GH/y7xZMqX6UKTnUoxbV/m+pbKg5kO7GBNvu+wKlvuLzpsF7PMdQRIVGx8bLE3/UFNRWLUFU+WuGuvK/9edyvXWJEXc7rsy8lGTLRJxXKjJOeRvqG4vD2ImSSfnQY49Ao=,iv:hoYjqj+5iilhWSDLRhHNmbjlGzVXDs25DWRZRBxrSQk=,tag:Vl4shgEqX2R7ktHSbRlx7g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
