# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:m1V4R1IkluO/Z2vOY1xnrqWy,iv:mXtn3PDmht66PGHCG2hPq8ZkW23Iq60HejXS3tW/ptM=,tag:88AcRST78VIDUqwEm8g0jg==,type:str]
    api-key: ENC[AES256_GCM,data:jiMAgtm04ksiWBEcDDyvn0A3rOTO+fIMcujhE0lmA6WrET8QfQ==,iv:qvHDPeMyjetXFBuX7IK4Dcb+OBO8tPhn6QUUQ7xOTI4=,tag:WW6/uUOsU3N7r/Ppt4h/6A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQUFRDT1RVVFY1Tk9qcHBT
            SmFOODd5MlRLaE5rM3JZcnBueExVdWpPOXlJCldLTldITWFVdlhvN1RsOTBGaGhF
            NE1qeVp0NDRKbWJPMEJNQkJhWnZydGMKLS0tIDRka016bUpvTUZvUE8wbzFaQXZH
            TFdXY0xMTmtjQ1pPb3JzSkg0bDBMM3cK4v6oQ+YaHjUYfSpCyNoDNeCkCp7ZKRGd
            4wjRlb5LJGkZWRS4un1yVIsb0EzDeFOL0aXB29/ZNJOtiyJ+yzbiMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-17T14:29:29Z"
    mac: ENC[AES256_GCM,data:KrO8XuJ/98gNtDP1cqRwzZnTgSwGECSfnbVkd+sqQGjxf+IsHCoOmxLkCgyqjJGcqQ3RWG14jY+6V54H+yS5Z5O8RHHQ+9HDi38JOd7XOOB64FbtX4H7IGug3D/4IqqlBb0zgt0D1j+PERylMli30AXOBC+s4o/hpL5dOyzM96M=,iv:UwcYEuxBC0x1a0JoFhXtbkCXGUd47Vf7PLrx7cBfoVg=,tag:AXTnMH08Iqgj5go6v4XJ4g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
