apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:N/PgTRzO9u6xfnk/CYQNOyJY2RRTW+jZfoUstCFiZeA=,iv:h7LAk70TEIoE+f9ZAVmqEAQbRP3WB/D45IPuuXC5s4I=,tag:IibzXyS4K0+3pq7PuF5NvQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBITVczdGNqVmZ3OE45RDha
        Z2I3WnY0dUZzM1NUTGtnV1pZaUI4L2NnTlJzClhoS0Z1Zm83NDBWM1RHbHU0ZVkr
        Y1ZsNXp6bmtGSWF3WG43NlhBZTN2SDQKLS0tIFkyamlhVjNSeTdOcHdiYitsV2cr
        UEdJRGthMWRNTUFSKy9pTDhVaUdGU0kK56w08kb3n5vzca+/93DxjVo3WFhc0nbB
        GL8Amtf/Rbt5VjjUJ/aUrWRUnr/SXkoYlU4XxrdLOYCIVg/SHGvGMQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-23T10:34:30Z"
  mac: ENC[AES256_GCM,data:x/F2bxzWQW4nJ6Czn2SBtcWB1MZMi79mWXyj8K1hNnQegNskhGMCXc6UP1/GUXF47rkyvq4LX4pRaLxznAk4VPo3lC8NKj6U2HRAsZyjCZqAaKuMgi6Tv5+nKMQ7wipo9qkxIMQbG1/F1CVZELeq/tZm9MeuYz0GB3cqpMhs8ts=,iv:NYOkZFmcYtBAz2eLIPmSRrTeOanaVwPXbYwbjvyPKH4=,tag:cU3x/rO44v8wsO5+MuuAjQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
