apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:ZF8JqxtcHgmeZj5nRxcpXZ3iR4x+Dey1xA/SOuJ3Kuo=,iv:yt7yhqFwbZAdr0/XqJd854qR/2k/f9OM7X0cVVlYUTw=,tag:A8L1PEmt6KLuDAuXQj6M/A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJMHQ1UjFpYWoxNWtOV0cz
        QVF5Lzdvek9iZjRNM2JaQlQzLzJzeG1ycERVCm8zRUFqem5JVzkrazQ2SVZ4VXph
        MWl1ekIxcTl6Rllncm8yV3BTYWFEMDgKLS0tIEkrb1VFejRpVFB1aENlZXdLWTJK
        Z2EwYjloazkvQkNZQmYzMWxhdXp6dmMKTBQTAt6rN1ES3N+wvlYyXOy0ndW0gSpZ
        dE5Ti5aDE5iY8MuMbipa/Dn6ktZtAOq2XP2W9gZT3iu/ccTC9wuXGg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-23T15:18:04Z"
  mac: ENC[AES256_GCM,data:PRyDSrGE3a4lBzYFXLJLQOlkachEJfUEGsvikcNIgNgbnsfbgQnB/r7AvbXETMZNlYNkQFfYIkMyx1Mz/EyHTr5gw0oVW5g0QzsigKTouIUWQ+Bl4zgyQt3HQ2qwy5vFPP+9XX1eYHBWsBWT6fTt5eq8PLIikuO7MMIyKHRQvgI=,iv:NehzY0xtm9FAa7E+Hi3AaNJ53mpaQsNWRvf0ySi7Hco=,tag:0xtDkTk892CyBJzygf9esg==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
