apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:1FCPmb8MJobigUz6hlrltJRiV1whPGduYMveRnFOyDA=,iv:0IZlGOyv6WTuzI5WfAEv7Cp70QXOiVcsBUYjZlsTBZw=,tag:fXFYA5FtpAhxFowYZyDtCg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5bXRKM3NFNE56eDNFVExP
        MVJPWjFwalBOZnlYU2padmNXNW93OW1POWdBCjJTT291NnNFZ0Y5blJ6T1ZGZ0dP
        bk9jdVBXMG9xTE5mY3NLN2ZNT2NaOEkKLS0tIFZhdm5HUXFUVjIwZFliWDhEQkJ5
        NXlMY1J2a3hJNjh6dVVqRUJCNjVaZDgKjwKn5becTSDHwEsi2cN7+sXXAm81vBlB
        Swh/hFEA6jhRRDModLVJVAq7StF5LS4NiPAyNvnQ9jaqb20Pe2in6g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-23T13:42:07Z"
  mac: ENC[AES256_GCM,data:Jhc3fVcAhnoGKlOjGBvUeoL9VThpB8UF2xdKGew8WwxloVAOXdqTX2sBkJqORpEBtFYCtBgZm9W1IQGrvr92DpRN8ncIaPgv2QXAxc7bvMue6W/6ZPEpIF4+k197Gg9RaIdyXcyVtze/myvajZBNNfamYs8bYmRJuki7owEdh0Y=,iv:vq83DiX3izgOb5O5lBZSYEiXtF79TitPStGj3JG1U0M=,tag:+Nz/QA5nz4chE3nrNzWbHQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
