# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:pRZ9rBXX5xf+dZr9rDBcHM86jEl1QbtiY2kg9wHYEWNPNettCJKH3Q==,iv:TVXGiqhklc69u7IDe8tuej6QjX9cjB3BhiMtxCsUWbg=,tag:fM7xhqwHXVVkpsYRfZs33A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjN2R1K3VzZEdzUkpKS2xX
            eHNYRXNhM3d1bzE5NFNRblNwdGlWOHV2Mm5FClR5T3JyTjduNkFqekRGL3RpWUJZ
            Qy8yNkNiT21zV2xLdlhrODNHT2luZEUKLS0tIHBObjlORHpGZGFNb2dtQy90Wk0w
            VVJYRzlVMTNTQ3oxeEdXU3dmd3hZR2sKS1QXIp4lXC7IU5uSjOvjJZtN4abYh1o7
            ViW4qqVA+QSGUVYOhq7omvESbKabbM0i2bRv/2/BSmPASOUElncmSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-09T08:46:54Z"
    mac: ENC[AES256_GCM,data:cv8WZ7aRD89GfdA3Ld42jQ188n++JCbEq1y/dRLXiO/XNMd9/fmds7+e+gx599Fypq90/kRgcLlglBQ+jS/BTxwnnZfsMKSlk1q3nZgnRBpelT7Ta9pW5/GG6OWiTxZ7fuHDtMlvWuEDr8f4fkVJe/p9K/3RD+8Nr67mRxRW59k=,iv:MVWlu7Qdz6tAHfBarDZz97NUKYDHZpfQHSUBG+vcJWE=,tag:wY0p7k1sLWqln/PfuOtTVA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
