---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: esphome-config
  namespace: home-automation
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: openebs-hostpath
