---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: esphome-config
  namespace: home-automation
spec:
  accessModes:
    - ReadWriteOnce
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: "${APP}"
  resources:
    requests:
      storage: 10Gi
  storageClassName: openebs-hostpath
