# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: zigbee2mqtt-secret
    namespace: home-automation
stringData:
    ZIGBEE_EXT_PAN_ID: ENC[AES256_GCM,data:JDoiMVCHClTz3lmi+GBnx1jY6z3mEQ+Y4mDtjKxF,iv:c14Elio7gF2cQOjQLqRcbv6LDDjWW9QmDImf0KZy6iQ=,tag:wXRI/VhVgf1JqiLl6CSWwQ==,type:str]
    ZIGBEE_PAN_ID: ENC[AES256_GCM,data:2JuUDA==,iv:OXx4SLcPdOk5kcLW1cBlgxmgOcZMGfi7yYZWofNdrME=,tag:te+yHYG/EtCHCfXDII0FPQ==,type:str]
    ZIGBEE_NETWORK_KEY: ENC[AES256_GCM,data:qhGbzeF5otLeimuSkljj+9fonI8/K+CrX+dvbVRrAAwkbCQTZLcn/8NGxnu98BjTjcbXw+4Jd1WSzMgwqaG0zlLIt3OChg==,iv:EJREfiWnS0lXTVpiPKwpIoY+mmo/1sTMtXRx8mpra5o=,tag:KPNvAjCnAub9IJJtPUw16Q==,type:str]
    MQTT_USER: ENC[AES256_GCM,data:lQzP/4pIqm/+q6w=,iv:f2BqltoYh5A2sLNhQ6bT3cqhy08UBQY+pyFoDqjO0Gs=,tag:atWVqruXxJ4I5fMfAkrcjg==,type:str]
    MQTT_PASSWORD: ENC[AES256_GCM,data:QXJfEfI9dDM=,iv:UQPwEbUolhfnyexKLRJIuCyCNeguIZ/h1VmOXOiuG0c=,tag:MutOdjxghH4cKv7+TXS6Qg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzeG5HOVJyS3EvWmJrcEFv
            VDE5cFFCYjlER3Z2aHFDR05NaWxZVlNyUEZnCnhXQmZ6WnNjN2NjSm11UFFxdWd0
            Um4yd2xzbjd0Q1pOOHRjdmlYSVdleG8KLS0tIG9HbHRybXFwZUdDOWpOckhzZ3BC
            bGtkQ1ZQQTRiRFVMTVpncXRTUWpSem8KGcjqo/FU5n5UYBI3f5DuRgS5xO3grAsx
            0KDiGYZ1IsdLyskBmVvK86V2hjsa051l2JHtmCj5IYNqDpoaCY3xkA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-14T07:43:45Z"
    mac: ENC[AES256_GCM,data:guCuB3Ky6m2hnDWvCafODeZ0CRdtP4OoZvHqXjWuTd1RoIZkGVOW140X52R7WEPNG6CgFZMiNU7/NrWkTMVEvcO6ptfmL+dQrUC1PlcgQVBIZYCH/fpQF6wQ2LNFitga4GbNierZ5MgaMXlxVbo3fePeZwvsbpZSLxItNfttoss=,iv:YhUA+FwuYYTj4LYNwP9DieAu/x0SirMMJQqDy1C07jY=,tag:v/Nkjg6dqVJM7HsbHdUJ5w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
