# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: zigbee2mqtt-secret
    namespace: home-automation
stringData:
    zigbee_ext_pan_id:
        - ENC[AES256_GCM,data:i3c=,iv:lnDBHOVcLmBAvz3W9mS0IorbqNrGTtzqT08nn6hYu4g=,tag:PVu7LlJMxcClIMzzFGQa9g==,type:int]
        - ENC[AES256_GCM,data:gP8=,iv:I11KQM9YQkfgYCY51ZOjNmsQxoXFCOMsS52uLCBFVYw=,tag:em0gM1Vv1UChcR+x7dnwCw==,type:str]
        - ENC[AES256_GCM,data:j68=,iv:pL1kwNeL71izrSX23j9l6ckiIGn+w0bigas/zVBAhvc=,tag:y/2IcFgEjr5VQ8SgK0VRKg==,type:str]
        - ENC[AES256_GCM,data:4VQ=,iv:OlhGRfa7LlPzFeL9FQa78w5U1m0F66pq1R/Afz55gs4=,tag:cJbsqSlvPAJSrIubnZmI7A==,type:str]
        - ENC[AES256_GCM,data:6eo=,iv:ZqDr7vOzvQa/Rg+feIyrGppci2pPsoPqMlEz3D8a8iQ=,tag:6zdYFkMPKE1vs1f7BsphPA==,type:str]
        - ENC[AES256_GCM,data:Iqc=,iv:VEBmkYdRlUAR5nm1Ez5qFpI9qpG4Lly7bYGB/z2StjI=,tag:GQ5QDzJ5Kta/CYiBXil2jw==,type:str]
        - ENC[AES256_GCM,data:p6g=,iv:L+uGs+SFvirZIkKVEW5GVFx/D/tnGNmA2Vw9KKPWifM=,tag:CzRpppax3bO+pID7ZffUqw==,type:str]
        - ENC[AES256_GCM,data:CiQ=,iv:sTOZ8kufa1v6tw7nXh5Q/SJnVI940wmz7HtucGvRijc=,tag:HzFrfCvTA1F/SbxNTZz4IA==,type:str]
    zigbee_pan_id: ENC[AES256_GCM,data:xvEBdQRVdHE=,iv:/iS/nH2HkMAZ+Ea+kxZiHtGAB+b5dA5trNgL7BR+stg=,tag:pS+Ay7gBPhYDXMg07OyKEg==,type:str]
    zigbee_network_key:
        - ENC[AES256_GCM,data:rcc=,iv:ARsENulaQSdBBKSspQdTWl5HKtFKWmp0CJvt0Wvl1mA=,tag:mqsRIRR9WAqN9LqeAnXglw==,type:int]
        - ENC[AES256_GCM,data:GxxM,iv:8LlsaciyDb3iYFLBOAL2mQgAWIsk5HI12yBFPT0sQwo=,tag:Mfdf1qHkfZWGArMQD1dICw==,type:int]
        - ENC[AES256_GCM,data:9i0=,iv:A26LUEzSrCO6NOvGRUuYIGGJ5VDDca0vFy8w8pQG3Gg=,tag:jcuEs0AoJH1k13CQTP/EnA==,type:int]
        - ENC[AES256_GCM,data:AiyV,iv:rgb8Xay7lLkGFyOPqrGc/aBotUre+dohu7fxrz6fu3o=,tag:l/+Nf+pGL2lXlXlKLFF25w==,type:int]
        - ENC[AES256_GCM,data:eRig,iv:8rFzm0RJjwMPcTQCFhm3Mcqf7V0/cWAT/I/k5xW89Ns=,tag:KUycC7n9ounw7+G4ONw4jw==,type:int]
        - ENC[AES256_GCM,data:3Gk=,iv:87ZDPzKLnN/y2HhwT1E2D/ZH6s4XFevsrtkzX+Qcoco=,tag:FVJZcllapxQg39TKPrrIeA==,type:int]
        - ENC[AES256_GCM,data:qzxa,iv:aCJrMaqw9pwsrvyzSKckjFlGwjPqWothqlKC8ZdCBzk=,tag:c6Kmyx42lB3dD2LI1Mhqrg==,type:int]
        - ENC[AES256_GCM,data:G48t,iv:WTIGD2DvDJ6kRCISaUMZznaI+qOaaJYvqnrVxpevq7Y=,tag:R9TzOnj6RhnpRLnZMgVzfA==,type:int]
        - ENC[AES256_GCM,data:J9o=,iv:lPnF1pyETg4X3M1bHLVmm0/+80ZYSwGRaFuazicWXzQ=,tag:+HXRd4pkxkL2LisS0QvlSQ==,type:int]
        - ENC[AES256_GCM,data:Kg==,iv:q55oy3xGuq7YnZ8id5oBPQL2TrcpLya+32eXbWxcRak=,tag:dSCMC5SAbLSyLICN1szwmQ==,type:int]
        - ENC[AES256_GCM,data:Fgh/,iv:jXalMCs6JLR0P8He3BT2s3clacpU51B7zcXSI8P932A=,tag:sqR5wywGLmvRzXb39fWfQA==,type:int]
        - ENC[AES256_GCM,data:D+E=,iv:Swc7JBKr36X95wlAluKSpI56KqZ1WqrqTB/dgMFQXY4=,tag:DP3kKC+jOYmdSeTUP4Hn9A==,type:int]
        - ENC[AES256_GCM,data:8IGa,iv:gDxZUGXTFtEfAdiITVWsxxj/byyjImIVRhTsMTxaHyw=,tag:/CsQf812LtBp9d3DAOJyrg==,type:int]
        - ENC[AES256_GCM,data:r1Am,iv:nRCVh2ImTA8QPio7brrmym2IURu9PSKusBwBcRxiaWE=,tag:Bll1B8NpMW9M/BXDYWC95w==,type:int]
        - ENC[AES256_GCM,data:/jM=,iv:eoLZDJ4v83NXoWIjZQy31CdT9ZLAc1eLoAu87zRyTaI=,tag:xKfWMqlmxT725W3A5AP4+w==,type:int]
        - ENC[AES256_GCM,data:DOPO,iv:1kqVOgl09/uZHjdTqenSIs2hy/zMPNUAw81UOujk/lk=,tag:QyTgskQb5BDI49LJmbvvlA==,type:int]
    mqtt_user: ENC[AES256_GCM,data:bnGHjRxZgIqTZQE=,iv:N7fK3sRcAHtUbbZgq7ZUtz62WWttwI9OkwZbriRGmqQ=,tag:1shsa/yxpHQt5WDSOB+d/g==,type:str]
    mqtt_password: ENC[AES256_GCM,data:8XfAF0pqTO0=,iv:fIzoGRhGWwbEfoRbRHrkErqhwOiAq6+JyGFlqgciz8U=,tag:smFDos/Qd7DdlLICZtDp6A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzeG5HOVJyS3EvWmJrcEFv
            VDE5cFFCYjlER3Z2aHFDR05NaWxZVlNyUEZnCnhXQmZ6WnNjN2NjSm11UFFxdWd0
            Um4yd2xzbjd0Q1pOOHRjdmlYSVdleG8KLS0tIG9HbHRybXFwZUdDOWpOckhzZ3BC
            bGtkQ1ZQQTRiRFVMTVpncXRTUWpSem8KGcjqo/FU5n5UYBI3f5DuRgS5xO3grAsx
            0KDiGYZ1IsdLyskBmVvK86V2hjsa051l2JHtmCj5IYNqDpoaCY3xkA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-14T08:08:56Z"
    mac: ENC[AES256_GCM,data:dXlvfykoS7x9r8N0fIctgS2LPr0t+OaYk8bdEzu9D98bhTyOosSUBjXhO9f96/MphLsnBMRSKvZvcJExQ14qUge8AdkU6Rda2V6baWPSadPPQpzZ/z68fuCJj7P+GbpoAJSy0ddOib2RK6XVNDpvH4TJU/8tYANNwtX0bfckdME=,iv:98MB6IofH4rwDYJs2TdHjEUTfc/aibaOeayXXmwIKiU=,tag:iJtj6HhZ/y+Miq6G2thRLA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
