---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/clustersecretstore_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: bitwarden-notes
spec:
  provider:
    webhook:
      headers:
        Content-Type: application/json
      result:
        jsonPath: $.data.data[0].notes.{{ .remoteRef.property }}
      url: http://bitwarden-eso-provider.external-secrets.svc.cluster.local.:8087/list/object/items?search={{ .remoteRef.key }}
