---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rook-ceph-dashboard
spec:
  target:
    name: rook-ceph-dashboard-password # rook-ceph expects this name
    template:
      engineVersion: v2
      data:
        password: "{{ .ROOK_DASHBOARD_PASSWORD }}"
  data:
    - secretKey: password
      sourceRef:
        storeRef:
          # Use the bitwarden-login store to get password values from a Bitwarden item
          # does *not* contain custom fields. Use bitwarden-fields for Bitwarden items with custom fields
          name: bitwarden-cli-login
          kind: ClusterSecretStore
      remoteRef:
        # This is the `name` of your Bitwarden item (not the id)
        key: ROOK_DASHBOARD_PASSWORD
        # This is the property of the Bitwarden item that we want e.g. password
        property: password
