apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:y2t2Fk+QMLLO9e62PAaYOlu5YExUaDcOUYu+CZnAHuY9j8WqWfZjoA==,iv:JOLbVeTg6Gum63JA3X186Uwcq+vQ5qhPn38HcU2N5zg=,tag:Ojfv+SCwjzJOp1WUZEL13g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qqz7ryljcrncf70a6n0yqptdq34nte99uj8j6ppucw94npccad0q304pkw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJcC9OWStmenFCcHNEL0hU
            bEY4ang2UUFVbFFhQUFyZ1p1eUxRQURmNUhnCnRiZ3gvOThrWlBFUFlaMUs4bm1M
            WTdYazhpVkZiLzNYRHlEVDhIZitMZjAKLS0tIFNETWhyd1BmRG93a3dOc0NZdUJo
            Wm85RlNkUGJEUk95ZlBhbXU2cEdGTkEK5fs3rpU8BUTgmMsCis3rWZ+WLBQTbcKU
            ryb/dLhRV6cfSErdXN5XIhERqT7EKYpusx8SRJGSRVWkqQf/47n0yg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-04T14:08:19Z"
    mac: ENC[AES256_GCM,data:26kBNzA6DdlOk7itgEaM5XjYZAdzrxnXUmdYwvxwxX804IUW0nyom/ESgTJQ06VfnmKIs6FSXFvDAXyyYOGIqDJQfT0tKYwqDOnos0Ke+62o6k+sTcYHpMz8PQmB+tocTM0etxFieJFuvmpZ2FhPX3guJfxfqniLoQPQJW5ddZk=,iv:K0mma+lSSN2rtQsxkGE/6eovkYDC26vsn3OxBwu27Vs=,tag:dibB3dASDJsbUg/Doq7l6w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
