kind: Secret
ansible_user: ENC[AES256_GCM,data:JVaqdanh,iv:ZWQo75ezY0zN8AlMp0tFyEPxT2GOWIJlQuHCzlJQZYo=,tag:IX2Z9gDNkN//l0M7XLlIpg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:31jhvz1DNuHbX517fqLWqFj6oFo3+36Li8S/k9/rYVV3WePv51r21IM8vz2x,iv:c1edUOzzMrTknueVxq8SUdTLUmQ0u9GRANAMP0rXCYA=,tag:l6YT3uzyWS2KAOizO3FOFw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNRTV1ZG15cThqamh2bjZ5
            aURJTzNPL004UlRQbWM3ZHRhNG5oSjdLZUZ3ClA5anptNnpUQmRuS2pSZFc4RGJt
            ckVIYkM2dkxpWTRKS0ZpckRmSWVyNncKLS0tIFR4VTdrbUlJRkh6U2ZGQjFCQzJn
            dU1Pdy9ESXVyaE9GVEhEcTdVK2E5RjAKddovqTnPYfQFw7sbP/MpuXDeJZN+nGbV
            YL6CllG5hUCcoaUHfIcKMmnOZm9i8THva2he5TPZfimXvJmZr+5pCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-16T09:12:42Z"
    mac: ENC[AES256_GCM,data:inmtRoJSMe6bE95PkQV7/+E2L9b/QAA9eaCpEABcXcvOJ6G/xwp71YP1D0MCYaTXG9GYMeAakjO0kl1f7ArCGpkPfFqdoA7CyzzAMbS0mrfV5xcVA9DaA5yiY22tnYkrVzMUhp8niGYlt+QRhi8xdOtA47webd3dzxhBK2v6P2A=,iv:WPdhhLgN8wjoiRntwcglIEm8R2ZGC7mj4LqEE79ZfJo=,tag:3tG6c64maULTC3yCkomEIw==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
