kind: Secret
ansible_user: ENC[AES256_GCM,data:Aef7IyA/,iv:r/pRDR8+DOdEmDQ8b8z/E5EPoKEHklDHnVeuwgylzRY=,tag:MexI48dr7zOlQYir7bCpGA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:OopSdR6o1BvjO/WpKkBtc6uCZU8zK13qcr5ufrDP7yFYLvOXn7Jvj6n2Mn3T,iv:JtptCrXRg9pL6arGVxaBvb+9ZPWK85mbHtlJAChoJJA=,tag:bYs8p69k3Siel+Tu5M6Mig==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGY2FsWCs2Q1oxbjM1VkNG
            YmlXSjZDY29xVFJjblh3UkVwUWl5clV1U2pFCmVNc0o4enhJQVI4b08vb3pVWGpa
            VkRlRWZwQnEvK0piQmh3M2NUV3ZHU2cKLS0tIDlvZ0JVRnNTN3lXSlEyY1kwbXgy
            UnhQRlMwVzlNZzAyYlJSeVJVYm8wenMK/fGChCHsZt9taYsv5jOES3dKicxFaUas
            qCBbITO+tn7xj3Am77EhquCGkWhJIPFCZRU7zkqnq4plmPgl0BxFSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-17T04:15:18Z"
    mac: ENC[AES256_GCM,data:VZMqGugKxP/AD3NgoQYB5afQsoJWjG9m/52oWJpKwAdrN5F2TDIL1ZziZnQTQ9UZuIaoGwROtEEjgAZ8CaeolMss46WRHUXpSmY1Gkw2keMTuNVwnFVCXfPNxg7u/IWWSqC/RElUH6lURPpp0E9OpWkm2BDcml8JiqvEyNeFWPA=,iv:Z8MAYXXVn49LcMcVBvhiEUdRT2wn+jnFDQIeOGzJhkQ=,tag:FDn+QK6qz+9e10ZyM+/W3Q==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
