# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: k10-minio-secret
    namespace: kasten-io
type: secrets.kanister.io/aws
stringData:
    aws_access_key_id: ENC[AES256_GCM,data:QYO/V8lhfoZWHVi82Sw=,iv:nOQTO8vYJP7gEzVO+mwPRf859MireBkbIEJHyKZB2L4=,tag:kHnoVwIxkEmNVfzlbXUuNA==,type:str]
    aws_secret_access_key: ENC[AES256_GCM,data:G5c2VDF6wLv5vUoVoucoIeXNgUXPrwovRQ==,iv:7qYoRRjpAQTSPHCAohA7bbDZ8lN+mFqBlVMU8yCjoHo=,tag:Z1g8TXSuPDfh+CPibmZyZA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1dHIwaEtVLzJOL3dSNVVk
            bXFKeXdjdS9jR1pzVkNGMnYwN3RvMDlYTkdzCjUrV0JuVm5SN21JMkFmM2p2L1V6
            R0tqNWdMZTV0U3lXaUJVMmZYZVdkVGsKLS0tIGp6OFVPL1ZDS3B0d0FyM254T1JY
            WDA3VG5hOGkvVENxajBIZktPV3NFWDgKEx14ra7EUlz+VvIwwkm7uIc6wuPXZY1D
            vMD5CApS1GS48YG4JJDjOs7He03etAvYyc4LChsOom1nSbpukg0u6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-10T10:09:09Z"
    mac: ENC[AES256_GCM,data:1Et3+xynBtRr+v7VA9IIfI7k4Ut6Wj/9+m97IQTOigVXc5Mlhl14SCkeu5YrW2rAav6vdNxXypFoYDIB3iBz5/6rBUsp70ueSC66uBw79UG1c1MGEwkvnKU+7n5Ac1ji677ANZKArID9YnfcGBFQ/bJjLlLfL9FpO8Lnc6ANx4o=,iv:x9CjempV5tx+iIsTLl4kL42spH+38VbkwWazkUhIxHM=,tag:77rtrgyW8H8S+2PWYd1u2g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
