# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:opGJjCkS4EIYR7xWoQI=,iv:lxP4st5ii8VKr0pjfXJ11Zd0J2y3ISfqKQPIVd9Nzqo=,tag:BO85dlIfaGGYE1x1bUEn/Q==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:7dSn1jjQveeAnV55G9oWzoCj,iv:CW+NvmVhaKX6pmasrmCYMTcqO9GwDJCcEGza9q9csxM=,tag:Pzl5uryXT843mjWh2dNR6A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxWC9HQkJ5eWhDQkZUbFVY
            a0wyVFBCQkczTHJjQkwrZHdJUDJjdEs1Z20wCnc5VzJ5VUxUZjBWR1hOMER6Y3VV
            Nzh5TWNRUXZuWWFScDgvc0RBMmtFc1EKLS0tIGpmaGlqSUFTVWIzckxvNlBUTDRm
            VVBTekxFT1c1bVVWSFdwNDBBWmVuTUEKn6UmqD3rjiKL27GciB240/mbFQWM/dhL
            kMvfATs1uxUhtDog2GCtwxQOvBR2c+jauAtyRw4xe9Mes5ZK5Yym5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-14T11:15:27Z"
    mac: ENC[AES256_GCM,data:lyHtKMRjDxj/YJFfPh98tG27h5nsVCDwJpaCPKBjO1dCaFy762vltpWhnz9jIVKx9y5gOeVM5Kq9xWMBx+3YwTjtDQ3i39Gp803o3KS4p8ATaLx0CsSp+rDJiJ8tt94W7XYKIiNNZz2KbfVwwJMW8I+XNSxTmXg1c043FYLgzfY=,iv:z58DDnau7H7wJ0X5bqTSS5UXw76woq4L+/Yo/OoberM=,tag:La9097Q4kO6yr9+8l1w6iw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
