# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:98qT78HRevSBAFnabpU=,iv:MjbQsAwRuJcN3ZrHEIkponxClSjynIRUmwGQqEMLBms=,tag:vIaWAu03bPRh8ddjrEUGDQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:3qzFMKP+vGAWpS4QcOQJCAJ4,iv:QcEYthj1Jp7TMmhhD29UkGEh2mtUXIgrMScO4xCrpFU=,tag:furkEEnjlsjwWkrswOSxeA==,type:str]
    PVE1_NFS_IP: ENC[AES256_GCM,data:k38+xMwkMmqd1MeX,iv:HEkCxOB+C2BRXzy78u4Ia7SyF6L/TlKlES6OVYyWcgY=,tag:QHAUHHA1UokeQ32nJxVowg==,type:str]
    SYNOLOGY_IP: ENC[AES256_GCM,data:wpbQz4UnhBjq9km7,iv:HENupn1GFZfvBYOsqvCG32w3wOGd7QwoOWtQY4AxzlA=,tag:WkPl1AodfqBOkQzotmpT3A==,type:str]
    SECRET_ZWAVE_KEY: ENC[AES256_GCM,data:2wXXEyQTh+XGNar7w6EjpZ97yRWrfupZdYx/Zf3qjn0=,iv:sWxl9ZT9kh2TlcTThVywQPo6Nn3N1V+UnBRFVFBVFDI=,tag:8UVx5MQQAzsYhaVBBLZYAQ==,type:str]
    EMQX_ADMIN_PASSWORD: ENC[AES256_GCM,data:u4uoHajxyqQ=,iv:vYLY84Qs8TGsHw/4CUlWB7osjYhdZkQrj+c4ZGaVonQ=,tag:Gy485Qp3gJ6V9VcJDVL6SQ==,type:str]
    EMQX_HAUSER_USERNAME: ENC[AES256_GCM,data:waJpkUcfC7jDq1E=,iv:fTbwMzek6acpkjG55DPuqLK/fNlkQCcCPN4lZPRTVQM=,tag:eZcQAJieghsuS5frm8NZsA==,type:str]
    EMQX_HAUSER_PASSWORD: ENC[AES256_GCM,data:L7huVYyeH4Q=,iv:e64kUmp4/CsKSD1YitH5uP05LT0OXyGgKR69TEK46B8=,tag:EU/lZ9LG1F7qPQI6bLTdfA==,type:str]
    ALERT_MANAGER_SLACK_WEBHOOK: ENC[AES256_GCM,data:QRvKflnKMm8de1YzrSB8jXPAvhdXXOxlJz8hFbRNQVkMrXzjaML5HubzL7YQze9kHRmAE3G5ZD2DvmGGVuJ+mvbdoDTHH8+PsinNQCJHLxIn,iv:yvq62o6V472IIg/2fhAfER34vmD0VpEP5nWLyxizd58=,tag:ZuSJFYyJO5kywxyiZ5Rdew==,type:str]
    GRAFANA_ADMIN_USER_USERNAME: ENC[AES256_GCM,data:6KHYKG9C+Zty,iv:qR/LZ7t+NDCWe3rL0aLCg04CRw/Bsqwg/GjyIijNcB0=,tag:PV/8ZM5wqNALXQjcRxbJgQ==,type:str]
    GRAFANA_ADMIN_USER_PASSWORD: ENC[AES256_GCM,data:pzKsi1DEpsjgxv06v4wtsdoC2Ys2LFE=,iv:sV8iz18w/8G29iSHW1KHbc2fAPHj4uiwm6sIszvNmd4=,tag:3WQpMt97A58jb+87dke6qw==,type:str]
    SECRET_BOTKUBE_SLACK_TOKEN: ENC[AES256_GCM,data:2Gw7DsnmvY5XM1nDZ3BOg/3aCg67r8PsoelAKbW1hqxgQNHVaolssIMoM6ECQYcMdetGVAwVoaOO,iv:zZtz0zwzSbE5zXTeGqbe+Mxv9ZFdTocPSOEwLPrZB58=,tag:tnWOKMRGAMsH5sYiQpQruQ==,type:str]
    POSTGRES_USERNAME: ENC[AES256_GCM,data:kmV9vN6VQHutzQ==,iv:nF7Uel6/RrxiIMC/caqCEFb/DKiVBa+GnV+w6b8Rytc=,tag:cvKbkSU1aPWWcpNe9Oh/tA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:E04wlBNV08SG4ID1Gnm8/cGCzht6Z0VE,iv:mzeZKzqNsYJ+/9BQAiyJNu5nhsulG5i/PCRpzcrKRfw=,tag:SIKEonfGfnSfodpWi/Wj+Q==,type:str]
    PGADMIN_EMAIL: ENC[AES256_GCM,data:UOp+uu6mt3pDU65yS6KiylUA,iv:AH4DolhoNXQi8YftvBGQsUw/5aHXe8qePYRq3YDjgAQ=,tag:M8MzYp9TJ7julRJdPdQ2ZQ==,type:str]
    PGADMIN_PASSWORD: ENC[AES256_GCM,data:UeuVj//kZfVgN9PSqw1UeqywrMnR/46yHa3c,iv:J+obEliy2crYl5kT40W+bo6UU9p698IO8fBB6BdauIA=,tag:Dy7A2a2f/ra/obqrqpKjzw==,type:str]
    MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:4zJySPbsGpznqx0sicZsUFh7IZ7TuRU=,iv:mq5QrZ1NvXFi8htb/S2Je3nmgaANfOvBI6PIH+A48DY=,tag:Ol78AyOqTz4kdUzs9e9WVw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBWStkM0ZERVJrdEY2VmUx
            ZEdaYUZFRUtUUWJrRlloRHNGQzRyWlhWRXpNClZSRnZJdVZIZXBpMXJ1QnFkR0hW
            N2pqM2N6YXlSeU1UejRtWjlMby9raTQKLS0tIE52QlVXelEzcVFua0xxWDR5T2w5
            VWNqWkhydzAxRHFvMnhhT3h3clM3bTAKVjj0GPOj4NEgqk2VlkcR4VrMV2d0pvor
            SneLyRfHqR4V1idH1ztsSaABkDd/yP3OU5g5pPFXariAacJA/oQa4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-16T12:25:29Z"
    mac: ENC[AES256_GCM,data:9tJMEanGLCRrJDpL+16VPQKdph0LLGEqx8XeraZvIA9kX906DFtNYMHfm+sGiKFCC9mhTg5OVam1eGWQrVF1BvS3eSe5LFPqQq+weuwWMA1EJZuvRTb3J2jibTJYtz7wyxdiYalH9xkFkDpoDwl5Gwltk8ZS1ZtY+jrijxPe5lg=,iv:oIYxQQKsWpPdaYA7tvmMCSC9iWbBHOyI3FqvitsMHjs=,tag:MD8D7BgHBZjatYVm+Mo4wA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
