---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  LOCAL_DOMAIN: home.lan
  ROUTER_IP: "192.168.16.1"
  BGP_PEER_ASN: "64512"
  BGP_MY_ASN: "64512"
  K8S_LB_CIDR: 10.44.0.0/24
  K8S_POD_CIDR: 10.42.0.0/16
  SERVER_CIDR: 192.168.16.0/24
  K8S_NODE_CIDR: 192.168.16.0/24
  TIMEZONE: "Australia/Sydney"
  INGRESS_NGINX_IP: "10.44.0.1"
  COREDNS_IP: "10.44.0.4"
  CLUSTER_DOMAIN: cluster.local
  HASS_IP: "10.44.0.30"
  EMQX_MQTT_IP: "10.44.0.31"
  INFLUXDB_IP: "10.44.0.50"
  PROMTAIL_IP: "10.44.0.10"
