# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:D1J4OuDrKKsW7SwE2xA=,iv:pBa1SzrdL9m8ceVDQbeaAkICbYGufgO9fgzM2KkdjFs=,tag:UyRcXjsDWUvoFlaVBJiwCw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:gxzd4cgLeWCJFDD9VPT+LVwc,iv:yQGwNRxhXVqQGNQP5MbG3Qzp3memMEApgfBpk6p8ncE=,tag:nYp989Z5J2ZV5k9tCu8v6w==,type:str]
    PVE1_NFS_IP: ENC[AES256_GCM,data:5hRKCRC2LK/O6v93,iv:ZmcelSVuUWyogZlGD349GYnakHgRyvUrMf9ADrX0Qwo=,tag:8oBm6DZeof1Ygo5F4386Rg==,type:str]
    SYNOLOGY_IP: ENC[AES256_GCM,data:Dt74SHSyHYhOoBkC,iv:KDjIh/ga9UnyYn5bsWpYNrcoO9ceh7SRtAvLS2p5gyg=,tag:glyWJKDMHz7V+BkJqSLxPA==,type:str]
    SECRET_ZWAVE_KEY: ENC[AES256_GCM,data:3AzpObX3lwfYsQQLWfB4jKEjGFGQVVqM6PtzPdN6ikw=,iv:eRadTw6leHM4sZkjA3XefBXW09K+xAWzGJoAcvW+sOg=,tag:bbGpTHSUjd9yZJ6J5qB0xg==,type:str]
    EMQX_ADMIN_PASSWORD: ENC[AES256_GCM,data:9/GqIAjpsDc=,iv:ZwWX8mLqeQwl/SOEJcmV/OpHyTC1WOXlcwVPt5vdssw=,tag:2Bfn172TypslJpSHKvVGpA==,type:str]
    EMQX_HAUSER_USERNAME: ENC[AES256_GCM,data:cJCRb44DVxiwyQw=,iv:iT4g7iuTJ6zXdlHyEFUG29HV4rPXKe+OGrPGQlduk9o=,tag:1dcOF+BGKpxGw4bURmZpcQ==,type:str]
    EMQX_HAUSER_PASSWORD: ENC[AES256_GCM,data:80P+SA5s3m0=,iv:QLXsDA7obLKtDBfAa7vUetd95thXlAYQlLoEIOWHSps=,tag:zlXj3aEAncNktslr2ouJJQ==,type:str]
    ALERT_MANAGER_SLACK_WEBHOOK: ENC[AES256_GCM,data:HaBTU1WA3a3YijD8xB/v4m9++F69FNNBsDCxor1QoRv+wTbAUCOEsb1jF055xCnw6TkWkTtKlGVUMuoBRxQ6GgNpzq5qbU2jb+zxg4+HLiGe,iv:hM8R+Yz4v3gKOWnUiGP5lO1Z8nCTpsKuQPIAD1kqVKE=,tag:E3RFLFCSmS/Dtyxp/P6rQQ==,type:str]
    GRAFANA_ADMIN_USER_USERNAME: ENC[AES256_GCM,data:7Pzm3t4g08jl,iv:RSL5/sZstyS57pzP7xepcAyRY6aCjy9JGBMa4oJnE10=,tag:5YCkkf2jva2br2dUYfrKMA==,type:str]
    GRAFANA_ADMIN_USER_PASSWORD: ENC[AES256_GCM,data:AfLZLfEpoD54DyGunwtsHHUwd6YjFNU=,iv:hcNLV4UawlYamm4CAd9TyCf973X2IYvyIqHXZa/NLi0=,tag:jHkitKV4H03H82dTq3c2IA==,type:str]
    SECRET_BOTKUBE_SLACK_TOKEN: ENC[AES256_GCM,data:ZTlh2qVVUJvfu1uk+KQaLLq6LSn9/IKr1C1ATSRwo0zmU3eC4/VOxzoZ06CsuW8KfJuwfONLWKx5,iv:oTUzUxbCZAs9hVyrxhQlYGDIFiC2pFmytwWOI++llrA=,tag:KEPhEWCvX+5jc/lw1Dc7Ew==,type:str]
    POSTGRES_USERNAME: ENC[AES256_GCM,data:tvp/96cTAcvCgw==,iv:djEwrKSicPsCerVXCsLW3f35w3jBzRD76/2Fso/B5yE=,tag:5Etd5xgw+FZ8DreEY6TViw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:/Zm2XpXo8i2u0w7ebjJScdUFZX+J8ODa,iv:ibOGuqIMWJfdsPu/FUNr4zgoKqb3fbwVeus4n8xm8mM=,tag:f4Ns/EoOKvT5F1emmvNYow==,type:str]
    PGADMIN_EMAIL: ENC[AES256_GCM,data:m3eQSBuV/paGuipl0BxyxAF4,iv:0A8DQch03f4u5sLxtaKelasguyN7uXFIzuzfDwTrVbY=,tag:95HSmgioxXNHKa5Y+C2GIA==,type:str]
    PGADMIN_PASSWORD: ENC[AES256_GCM,data:9APO6HaTK1/ux5LlbBbRhB1kt16587/qngHz,iv:IKvrZ/QEq97x0j6m7iN6/yDHPByRoEZLHXKaBzR2CGw=,tag:LYVoHEoAjm0OLUYC4qrr3A==,type:str]
    MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:VuLIJ9rCqmHN38wUKKRl4xvqA5UuaiM=,iv:a/LSL77LheSyDc9T6C71Wu46pDiNtYPY9e0T3yMWHtM=,tag:9JwgAUwh5Tr6Q1UZPBYmrQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDRS9XWWc0VlpBL0JROFhH
            cVpqb1NiK3ZhTkROL0YzQ29ONXJ3RitDRlRzCnAzU0ZPd2tGdVpKdVpIc1pxeitT
            bUtRWkhqQk01c0NEOTNZdjJVc1cvN1kKLS0tIDVVaThORlB5eUZIZm5XQzd6OU55
            N3JHRVhEZDZCa0VoTHZBWkRzWE1xNjAKPbWl9yIT27YtgsvRis1LHo16Kh5RFxkg
            SDWotgY6k8eITMGSb9cJM7s3dqg1qzzqwBefQdwRQZSwKc9ZVaX38g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-16T12:32:51Z"
    mac: ENC[AES256_GCM,data:Qn+2xvbh7mN/2M3+wwiQJ/fh6MiYSwH3bpKsH8t51fu5Tidnlm01ZwO7Z4K/YQ2xdzo8ZqnUqK3NsmSl6Qrb3Dgwh60Jb8vd0cat/OhpmlUD0U1VIWtjbo81e9WnTxEuAlKl7FqsVI/nNv7tDSp2xBUyvFT/Bsso4AmcKBF58WQ=,iv:CAYCCCaaaRALDgKLxHbVhUNnojVvWlKXBbeuXGo/cgE=,tag:rhrWddcxTiRIdZ8ePhHclQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
