apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:7FJsqUwKMiv5qs9vSrluVI41ElVAB81FDn8i2iYUI3Bu5JySEgYGnLSG3PrNnLY/svi4Q3R2pna5eqI+5IHg8JOi+DjOBUjwg8jsO9rjgOvNcR/WJEW2RyVhXvrDoYVKVf3tbLvzZJ9E2/x2TEhrX54hkSb/33+QucH+vH7Pw/VVBQdR2JhQTVofdcRFCMJBgT1LWHt8dIiLQL9e582bmutBl4umzL++RjlytK81PeZCuZn4,iv:VZTfZr1gtILngmK1MgrTqKJNupDA63bmnKwCLn4NCpQ=,tag:6F0tjCUIWRMamZFoA/H7dg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5cWd5QUlFejk2ais1bkk2
        amFUYXg5VE5qdmhnWUNGK2dFQnlPa1o3YWlrCjhmR0VGbkhxVTFVMzVrSnA3MGda
        OWpZRWNPbFo2MWtxZmRodGNCZjBoS2cKLS0tIHhLTGYzVldnS3NrZ2dxM3ZqNEtL
        d3RaWjA0STJ5TlJwNkljbSthY0g1MEkKkqeKZ87ozBxrOkgjF5P6S+OdmqdGVuMW
        lVCenHEOP2KqecXjYz/6S4hlkT5xJc7vHMJKV7b9Ucn0STI2b3+LBQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-23T13:42:07Z"
  mac: ENC[AES256_GCM,data:uU9ziUI+/PTsudkI3u0ETfogWicGT1VKC/UeAOuGTaaqZd1RpEqq2ro1C8hkAI65+tP5So1kRSr+vtAmsTCdtuSd7kHHHOIhrOzzT9ifLMG9aKsyjRUkhoRC+3fAchhjarGz3eWkwVEBfxIAUlOLWb0kiQ8ovky/k0ULbLs9cGI=,iv:Ej7O/3sW++nZJkD6YASji0xSACh8MptpxCHncIaR/R8=,tag:dOlNbRvmGc9rMf+2jC63IQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
