apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:tvCUJCAExOIebAginPUhFyhiiO5RR/bNzQlUPuGKJGGyep3hNsnLle5PGY9kO9S3B1Of9kNozapDg2W/tRHqPPz0OC5x137OSXdfnA0nLOvJQ3HT8jOJ6yhxRIEkOWaKZMMWCbA5lZgl7FHekdJpOVMs+YykHj6fx+XHs0YUF5UO1hTX6rkisTdw73bt+swcfri9FB1ThIm71c4YVSyI62XgZAaknchJD8Gbbvur45E9Un6X,iv:SQ/kmYkG93Q1zOwFAtYCct4Y3MR7GxIfXd2UyjhjLX8=,tag:7tUEZBPH2PaJOvTy+k1zKQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5akdCeDhqbEU2amFhV3pN
        dVFVM0ZxWnRMUlBBcm9FRGd2bFcwV2JpVWx3CmgxNW1GOCtDMTk2YXJJaDFWQUt1
        cG9ZTEZCMzR3bkowcVQ1dFVDcEI4S0EKLS0tIGZjTVdqWkQ2c0RkME1EdEhtbEVt
        dkttclRxMW82TzhPYmh3cFd6a3lXd3MKWF5rL3TEONgutu7psXT25vUCGD14COBl
        0dVEFYABVmAfHNRTwt8p+mc9Bl1T6CosLLAhgqi6TtTnU/kYz719/g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-23T15:25:53Z"
  mac: ENC[AES256_GCM,data:mhYYfPBhvaLA9kM+U0+lBTW2nJhJDPHTMJTefVP/ydc+9z+AMh6xXw6sehYQoO3xmkngKEimCNmqyTZOu3N+gjytbBnBxzFBRDv1nHO9aUSbemxttb0Kf64s+fMOK0gvyMSfr8zDKPS99egEQjXZdo7CRe9lPjNNSbqECi4hsrg=,iv:g0toJEhiiOaRl3v8BU/tyCsPs5wEp7UTcZEVj9FiIi8=,tag:XUukkU3pksYr7qqwpTCldQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
