apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:fFnJdkoA2FjaHZLU1QYns/LaFzB/tq9VnfBzRxSvxorou5Y0PdcYDA5YJ3tmuFLF5A8UL2ROAlFvwc2LCcYz1cnRSlBlQlfv1oACPWLqnRnXVBdozD+SoK9Nx+iIYEWKy3MX1UX8H7Fc2lhwZ9ZzA4gRAsujrNCa2SY/eCJmJebWdpJPRVAviL6eV+6yrzJLraWbCFiYKI7jH0Bw1XRMBZt14WT0jlmq3xSsCE1oBd4X9Y1w,iv:fcxwjblQenb1Wc9A0n40uP47GIP5ermY5Yme8ZWN+84=,tag:Uolzumv4UQ2CypVYIpMmnA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4a3E2V2xrNUtyelBGNTNM
        d3lmK0NuZEVDbWR0YThSY0dkNkJhYVNXMDM0CmhPV0JZcE5HelRNRUgxaDlselNs
        ZTRrWEZxU1hFNmtBRGQ5ZmVWcHAvdWcKLS0tIExJeU9qNG96TnBwT2ZMeTNxVWxX
        REM4WVRGVmlsR2Y5UWdZbkRNblhxb0EKaLNhFbYaj8SQ4iZwgR4HriMWK9QQm1ze
        7u9nCUSLlVWjvz0c59gYzkoe+diqsWPzg8QWWyatLZAqP6lQEgnnww==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-23T15:41:22Z"
  mac: ENC[AES256_GCM,data:RIDgAJJ87gBWwIMeHXJiBc4CFSJoy0+o+Xh1ydxUUVkOBKUxkJGHQkz6hmGSqaCW77gEQPsUbwzf/DkZwEBc//cXw6RHBnQyGQI1Sc6HqdeGcfne7OvbIT4kb3cLFmG8SkRWHZfjd5is03f4Nwh+B3KK6ZWKcfGV5+Fq5XP46QM=,iv:qFygEuVuYDTr/tZryV2kyD6SO1BNxQU5XH7opRYB6Bk=,tag:jZzOna6FfCoUqHAxZRb0Iw==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
