---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config-nfs-v1
  namespace: media
  labels:
    k10.kasten.io/backup: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ceph-block
