---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app bitwarden-cli
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      bitwarden-cli:
        replicas: 1
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: jessebot/bweso
              tag: v0.5.0
            envFrom: &envFrom
              - secretRef:
                  name: bwes-secret

            resources:
              requests:
                cpu: 100m
                memory: 500Mi
              limits:
                cpu: 200m
                memory: 800Mi
            probes:
  #           # -- Liveness probe configuration
  #           # @default -- See below
              liveness:
  #             # -- Enable the liveness probe
                enabled: true
                custom: true
                spec:
                  exec:
                    command:
                    - wget
                    - -q
                    - http://127.0.0.1:8087/sync
                    - --post-data=''
                  failureThreshold: 30
                  initialDelaySeconds: 20
                  periodSeconds: 10
                  successThreshold: 1
                  timeoutSeconds: 1
              readiness:
                enabled: true
                custom: true
                spec:
                  failureThreshold: 30
                  initialDelaySeconds: 20
                  periodSeconds: 10
                  successThreshold: 1
                  tcpSocket:
                    port: &port 8087
              startup:
                enabled: true
                custom: true
                spec:
                  failureThreshold: 30
                  initialDelaySeconds: 20
                  periodSeconds: 10
                  successThreshold: 1
                  tcpSocket:
                    port: *port
                  timeoutSeconds: 1
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: { drop: ["ALL"] }
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        #runAsGroup: 1000
        fsGroup: 2000
        fsGroupChangePolicy: OnRootMismatch
        #supplementalGroups: [10000]
        seccompProfile: { type: RuntimeDefault }
    service:
      app:
        controller: bitwarden-cli
        ports:
          http:
            port: *port
    networkpolicies:
      main:
        enabled: true
        controller: bitwarden-cli
        policyTypes:
          - Ingress
        rules:
          ingress:
            - from:
              - podSelector:
                  matchLabels:
                    app.kubernetes.io/instance: external-secrets
                    app.kubernetes.io/name: external-secrets
              - podSelector:
                  matchLabels:
                    app.kubernetes.io/instance: external-secrets
                    app.kubernetes.io/name: external-secrets-cert-controller
              - podSelector:
                  matchLabels:
                    app.kubernetes.io/instance: external-secrets
                    app.kubernetes.io/name: external-secrets-webhook
              - podSelector:
                  matchLabels:
                    app.kubernetes.io/instance: external-secrets
                    app.kubernetes.io/name: maintenance



