---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: octoprint-data
  namespace: cad
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: pve110-dynamic-nfs
