---
apiVersion: v1
kind: Endpoints
metadata:
  name: media-pvr-ext
subsets:
  - addresses:
      - ip: 192.168.2.30
    ports:
      - name: heimdall
        port: 80
        protocol: TCP
      - name: openspeedtest
        port: 3000
        protocol: TCP
      - name: jellyseer
        port: 5055
        protocol: TCP
      - name: bazarr
        port: 6767
        protocol: TCP
      - name: radarr
        port: 7878
        protocol: TCP
      - name: sabnzbd
        port: 8100
        protocol: TCP
      - name: qbittorrent
        port: 8200
        protocol: TCP
      - name: readarr
        port: 8787
        protocol: TCP
      - name: sonarr
        port: 8989
        protocol: TCP
      - name: prowlarr
        port: 9696
        protocol: TCP
