
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns-internal-synology
spec:
  interval: 30m
  chart:
    spec:
      chart: external-dns
      version: 1.18.0
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    sources: ["crd", "ingress"]
    policy: sync
    txtOwnerId: k8s
    txtPrefix: external-dns-
    domainFilters: ["${SECRET_DOMAIN}"]
    provider:
      name: rfc2136
    extraArgs:
      - --rfc2136-host=${SYNOLOGY_IP}
      - --rfc2136-port=53
      - --rfc2136-zone=${SECRET_DOMAIN}
      - --rfc2136-tsig-secret=${SYNOLOGY_RNDC_KEY}
      - --rfc2136-tsig-secret-alg=hmac-sha512
      - --rfc2136-tsig-keyname=rndc-key-synology
      - --rfc2136-tsig-axfr
      - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
      - --crd-source-kind=DNSEndpoint
      - --ignore-ingress-tls-spec
    triggerLoopOnEvent: true
    serviceMonitor:
      enabled: true
    resources:
      requests:
        cpu: 25m
        memory: 50Mi
      limits:
        cpu: 50m
        memory: 50Mi
