apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:fPdgQK0QrST7CrX60oa+bzi+tbqdtT1iVtiPym5aNEHnrUpJoBq94w==,iv:CDOuug1t4pZLQODiN1CnxS4zRCnEM73j0W5Nx3RYp9M=,tag:yHaCeHRiao2qu9w/Q4M2tg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLNC9UL3BOYU9vTmw4VlIy
        VjV4bEtvRExZSmh5ZjNySFdRa1NZMk05SHdrCk8wZllra1RXeEhBR3VlQUJGaExr
        NTAxc0V3SEhPY0FOZittQjNHRUFUdDgKLS0tIGEyV2dHSm40c2Zad0NJeTM0ZnB1
        ZzJKSTZhOHFMN1J0cU9rcEJFQXdaNW8KCU9QHsERMcUJpXMvSYwtKxi1JHEdVqWQ
        OdYHqUqhxEU10Ji9bqJNNksEQlu7yQo4J6tltb0+srl/EMIX3vkszw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-23T15:18:03Z"
  mac: ENC[AES256_GCM,data:PtLxyBAWADTHON87vTDGBkju/iq5jztxdsRKQkLIofUWlfGDtCMWmns80ex4oCwVBXjeXepj3YWNstBOjXrMJanVxCO9Nz3y9tOfTzGVqbVnnFfhMLpNbGx/OSOeamBTquEp8XQkEiNnpGcxghqJ+7Za0jRUB1DoKDVsNroS13s=,iv:0JBdaqKo+LtlO6K8+VOfmHmbk/9wLTpb4vCA7yrgSjI=,tag:giwdxfPb4WHhlwLSuDhvXg==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
