apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:kELeSA6bSZnxcoZD7K6XTrT0yuvm/oYHAUdiIqcJQ0C1A8U1FPaGmQ==,iv:MPpTGwkfNh+E7shNDyL20OYu/SKFPQkcRClOf9WnD5s=,tag:71FO1UYTc94NuXH8Vl+JBw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsSEFoZjE2dnI2a0VRL25O
        T2FtTnN2Tjc4eGh6N3NoM1AyS01OK0ZaTjBvCkVLQTR5SzlmSnNWbkUrVURoR3NP
        S05CY29HKzFBNWRUK1U1ZVZwVWxlSVUKLS0tIGdXUTlpbUxvd1k5ZldNRDJqb1FJ
        ajBzbEE5S1kxOTlpaTJWYmZVMHRTdmsKW2UWI7MLFD+FvlnEqiv+wF3/mPpghiht
        TY2YNlV26Jm4ymvRUSCFBnxBaEWkEzHx1QnfN4nGxMI+SHB9c86C0Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-23T10:34:29Z"
  mac: ENC[AES256_GCM,data:8QZZMrvXLO9kKZev3IR/r5aQB8Iy9ztafjnTOh5Ojye2a5OVuMJRmgR4RNyr/5dMkgg9tR/EEPYgMejF5mca/f7VHhiDfNIjEjWurH7E8CWv2GhEIFfW3rPhNj08v4RXiHtnZizrDnyyHWZJsxirymqeqsiVTijfNAz4aD2fPtY=,iv:q/EegeCaP1tLFO6Dm5nATJI7Ov67peCR4Aza6whkdOI=,tag:X0qKepzpN/mX8bPD8pNluw==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
