apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:gI7OnCe2umo7LALdvpV9rmBNautHVCiJE1vfZu7RYliU1yYBpHLCiA==,iv:RGL62awNJfqATno4I2ggWddETx76SrP+DLVczWv/jZI=,tag:EQSUxk3ZTjZBZVEyswGDMg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0OTJkcTVSZXk5UkJtQWdl
        dVI1RDVGSWJHL0lVeWpiSDdmTElLT0JUMGpJCkNjSng3bFBwNnNwNHlFQ3BEcDY0
        NHZhZGJnc3ZNWXoyR2daY1hSaE9nTW8KLS0tIHhHaCt3T21aNjkvZ2NjSVVONzZ0
        N2NLa2ZPS2xybWJpSUtRbmEwOHI0NmMK9Xi1WU+HL5HDO67xMl8/lid3KHztevrj
        Q2+Kb5ttAK4OWPiyzgOEZGeFoii9R9PUv/TGn+Ra8su7Fzo4I1s9fw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-23T15:25:53Z"
  mac: ENC[AES256_GCM,data:9LAvkXpPv0GSA7Zx4wBCNBE6la3Fw+K0zMeFMOZGtwSYS/qS/u56p4dTow03w3eZncq7XKD9PdTY7MNo5sZVQo5NXvzpqogMbayi2OJ/O+ndg8NpsOrCJGiTdIY4A+gQH2Gk94NvqG4Uw+fpZymVsWnsZdXoiE/tA7ppVjqGhXg=,iv:fMQW78zX9mJIkCPcSlY5mJDK+MIeQtoDiu5lGkWX8P8=,tag:q6GuGQwqQX8BfVbKoJdtwA==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
