---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  ROUTER_IP: "${DG_ROUTER_IP}"
  BGP_PEER_ASN: "${CONFIG_BGP_PEER_ASN}"
  BGP_MY_ASN: ${CONFIG_BGP_MY_ASN}
  TRAEFIK_INGRESS_ADDR: ${CONFIG_TRAEFIK_INGRESS_ADDR}
  K8S_LB_CIDR: ${CONFIG_K8S_LB_CIDR}
  K8S_POD_CIDR: ${CONFIG_K8S_POD_CIDR}
  SERVER_CIDR: ${CONFIG_NODE_CIDR}
  K8S_NODE_CIDR: ${CONFIG_NODE_CIDR}
  TIMEZONE: ${CONFIG_TZ}
  INGRESS_NGINX_IP: ${CONFIG_NGINX_INGRESS_ADDR}
  TRAEFIK_IP: ${CONFIG_TRAEFIK_INGRESS_ADDR}
  COREDNS_IP: ${CONFIG_COREDNS_ADDR}
  CLUSTER_DOMAIN: ${CONFIG_CLUSTER_DOMAIN}
  HASS_IP: ${CONFIG_HASS_ADDR}
  EMQX_MQTT_IP: ${CONFIG_EMQX_MQTT_IP}
  INFLUXDB_IP: ${CONFIG_INFLUXDB_ADDR}
