---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - default
  - kube-system
  - networking
  - monitoring
  - system-upgrade
  - db
  - home-automation
  - media
  - flux-system
  # - kasten-io
