apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:gdNwskZJ8ZcIgNsrToGPX4f29N1Znj4kQqkZIIGYto+2HLBqj9PITxTNoWeuEaN1nN2Yepf0PIFQuxygnju0Kmv+AchPF4qICRpjlpY8b0nVkgqWUwyEBNmIKBEl0w==,iv:Tz48sDE7AOP/sPb5TL95WKJ4Z4UDeA9Ypy5BYzSXR0g=,tag:IKpc89oW9Ga3rv0clf7lww==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:wcrXGJT1FjtEgJz4pZQ=,iv:E5p0oyU6/LPO0bREqJvs2rrEuz9gnAq5DEgSRCa2bCw=,tag:os20q3iCe2KtuC3wQzsLIg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:J+cYe1PXIdAGgO7HTxEacdWA,iv:p+RpP7mfMbgpM7Lr3zWBm12Wx4C+W+bWHnWbtGb5JMs=,tag:DUVsr8wvFa1zDhr0zYYeRw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:yT79rCwUI0zbpuC2yoJTItS0UPNCtJMgz2B290tudnS+7rmj,iv:YIHhz0zJnTzDqA01hmWWSjQZOMgpyJmQAEOaHPSMZMw=,tag:FLNAY59SEIjRJeOAjymkiQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qqz7ryljcrncf70a6n0yqptdq34nte99uj8j6ppucw94npccad0q304pkw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDT2NZWmVwQStKRWx1S0wx
            VTd5ZUgxdVZ5QkZuR3laZ1FML1ovK0xkblU0CmtHSURqVFROSWptaFUzeGJOc2tB
            dkRKVkVyWTJ2VEdOVnRxWEptWHY3NDQKLS0tIFpLTjhyYlo4RDYydTY0SXpEZE5E
            NVBtODRteE5QSHh2NUwyaGpTLzVwb0EKFERfoCTHe49Uqrkh9z4Ze8ileJKpa285
            GpXQMypyvzWGSvukU+t6XQsnQgcTEv94RQ8CTOUvywxK/USAdW9FCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-04T14:20:21Z"
    mac: ENC[AES256_GCM,data:4+KxvSbRRIFzJxFFzILvaooOu716Kr15MUaNiAzgU66PYW9O3zYVjXXqwMshpOGCaRSdts1CSFtKoaIlnBtAbNj6sVMQl4oO0507guaVoZIun2gzzKYRpfl87nYr1Ifa6BeO/I7vCbTU+IsUnQYk3b4LONm4nUWcOY4Da625hG4=,iv:TgfEeVqKdCp5w59JkeQamm0bedf+GHOlyV19VpwB2Gk=,tag:z8Lf5uw4aGmtqc5IjrbKgA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
