apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:J1U3kZggSl4nPFU5QwlYIq3DZekT1ZAD+SHQXA1qiNNPvsi/,iv:0WSQr9Ii+Nb7IpQFLCnzslmTCK8lg9g4zwlngHSQ7dM=,tag:6Fbc/4LUebCaDN+3WVdOWQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:sdn3+1CE5bru4FgsvlOvJs9W0eu1+Y0ETD6vv/CXjt+YFUuYJEZWP3N5Z/9OCEKveNo9DbmixVUb5beCTJ2bwFrJQu9DwCvDlVBbzW3FUwEJhgMuTq1GNXODFvTj2iinkkIlI1qRBX2Qz9MbeJymk5Irh6qnnS4gmji2dDWWxZY53JwDYCCn6BiTN3fOXlR5R7lKOE+VizcUjscJyNepMnegbZkt0VKYmpRACddqDQ==,iv:Vb0gJdlDe0iwqOwm6PoT7cB3Y/tW+5aPXWXukV1fhP0=,tag:W+oQTTm6O3+ZvL0DwDcxxA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1swfceavhed7qqdn6tq3s6dv3ny7m8ngk5z8ap64kk4ztumqgxc8q3x7eed
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBub0MxanhRakkvTnhQV1NW
            WWlNS3RyRjhmSzM5S0N4YlU2SDNZWHV4TVhNCnFSTi9rYWxkMHZ4T3Z5VDg2TFA3
            RnNmWmRla2k5Um1Za21SQkRSVXBZQlkKLS0tIFprWVVpaG9sVGlkTXdxenpaRmdK
            TmhtWGNzUTR4bjZSQUVkbVNJdVI2WkUKD73TNTkWW+K8UaGDwp0PcdDPzCgr/QsU
            d9zKbXzaeuFoWKlrZzT217HNKbWbJk6OHfY1w60zsPGLOGBC5ClFKw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1qqz7ryljcrncf70a6n0yqptdq34nte99uj8j6ppucw94npccad0q304pkw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSaXRISFdmQU95VktJSmJI
            WERSWCswRmJuZ2NGRjJ3WUlsQXVGc2xNUkFBCkJBRDNKdnR0a3ZYUmsvM0prYTdO
            WXZTY3d1VEtuQUVYNFVjcDFScGlUWU0KLS0tIENkVDVRdlUxaVUrV2xWb05UTVdX
            TlBpVmNNTFFta21LYmxKNlZOU2RITU0KPUfOOHb5WFPfZ7pKMqRWKy7pE5koildT
            mhgnALqn3dmIrvNhF61kn8y1UBPRT9C8wQVKaUhJPv3xwQKlguLMxw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-13T09:34:58Z"
    mac: ENC[AES256_GCM,data:wG/WqxrXRe2i4TCWJweSSV0Qfcc3BMgpCNUH0IPMXOYPl/8NYfpr/OtJSO2klHJICh2trH/fLGl6SFDePpbsr/03ONvPh3CSGkk7955ejZ/FBZbGhYa7VH8IhTS1RDCxcsSjfHVi68hGmLqPSUKzteiYuWsBCLspSxU36/0X5Nk=,iv:5oF9Zryxejz9DR3zCC9sE+3tBB1iKdVJnF62Ja/eN7A=,tag:qn1F6Ylb2oerGvFKnoYUPw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
