# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: github-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:B4FG7Foi0kjFiqlCsKtq4Tf7LhQT2nWVird+rz7NjH3JLU1NyZqgaw==,iv:e2uLwMDQbEd+DOKGl/FJY/o6naSVPOIm9LBS71ymDac=,tag:Gou10HG23x8p0YaJwYgVzA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEVWJEUXJ3b3QydnJPc0g2
            T1IyU0hnSndnc1pHaklzNWlCdjFHRFJ2OVNrCjlBVEVTaUtneUVoZjcxUE5EVUxz
            UDBuZTFORmlRSTdiK0NIMkc4L2ZCdTgKLS0tIGFNb0FIMXEzSnJlUnU2Wnd4MmVi
            UmIwYzFtaFVjZVJ5T3E5QkdrTHJwdU0KAhd7dkq7klarYywnmHH+b+1toYeVdL0w
            HC6245huev3DfMskNH6oGscWHHZswlhQspxZqHrV0Gppm4PwwbpD0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-13T09:00:59Z"
    mac: ENC[AES256_GCM,data:XI7xglB1oAD11KmEz5UphYRHQUlzBifp2mD6tNfQ0yyXM/oKm8asNrF/W8ImEkqFi5KNVpkMlhosuTrxOPB96JcJYSwzjsNrgtKutz0oT0qE1wkwkH+Vk0lDGsAmtaY/lkX4ZU1gvmDK9XpjkGMhSQf6L2eHIkpEprF163espVQ=,iv:mzwFZhzdSUW09M5MeaIECmiLkOcDUb3hgh9bIuQaybo=,tag:n2eIrc+mr71s6PO2jZrdww==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
