# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: github-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:c7eVn/lZZCA0UmB2CRdLfn9Z2NRGz13uQn2sM1jlW3zPobTg7fDR3Q==,iv:UxD91prXH+gsSDXoQCOMrmGOfFCzeGNSF72MNPeNYsY=,tag:3Oj/oy4N/9HT6UdQb7GhnA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3NXUxRU5zb29lQitNTmhN
            bUxjamZ4QkIwbjJKeTVEY253QXdqU09EZkRRCk9RQXVyb3Q3RDBlMGlldHpkbDlC
            Wk5td2MwL2ZmbEYrakRTbUR2Z1E1TTgKLS0tIHl6c29Tc0JwSVZEd3E4UGlPcXZa
            bWdLYUF5dERSMkV6QnpPNWcwakVkM3MKAni6qjXWpxXc//45b5JXFRzNxPHL/iXK
            6T79gnLXZsD54PCCqt2gH6Z7tzQNTKZsaK5Vae4NEUVEJIkTe7+gXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-30T01:39:09Z"
    mac: ENC[AES256_GCM,data:lxdM64uRnJzgbKcVgyBdJ/hyrnvHuYFuhu9on/Fc9sEnikCpc9EzlRkUtJOYVQBAP4DOKxaqrJmfWr8VhqahAmArkmV3Rl6mnC2upyyfJ8EEke+L2ZiS4hYd45lKwBf4c7w32ntxPUw9xABKwRRKintoPFrE7aHc6ix2aagQ138=,iv:G9AzMVfsxuETMAXbfqhP6rpkezEoESkiVj69krhnk3Y=,tag:oWc4IXn8DfnbB45zNnMpkA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
