# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: github-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:ESI6U0k/HbC4V21AjKUH84Nvnuq2VRlswS2Ug9zfVvAuVPGx+wA44Q==,iv:h8cacZyGtdIclmt0I9/iwm0T++oLCMaIRF0zGCE80OY=,tag:vZfnjiLYKm4djC4h+qro8Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1VTZwelZRbk5VTzd6Tnhw
            ZUZENlRFMGNjYnhnTnpXemtEWXFrZXpQekVFCnJQWmJPVWNWVytGdkc4a3FqNXNF
            cmovd3Y4cm5Jbmo2a0I4QmZQR3pqV0kKLS0tIGZjbVZIbVpNNE1JMk1Kb3RrQUsw
            bk5pbnBWeXpWUUNySDBZUk81KzhNOVUKO91meK2DCRn3FqVU7FL/Ymv9qOcfIKPh
            B0RRIXZmkEZ7uhac3jbDuxAi7avnmk33a8Qa0ZFooudj84DDYx19Wg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-09T07:46:52Z"
    mac: ENC[AES256_GCM,data:aE5nPISceLgYbQpSjXwAlqbkmAw8qCcALQxjB45Tw2NJPmSzkATv/uC+xfwXvmnP2QYHelAqHDHwMIpggXbuVKnnENpPqJayZWh7bQphBLEGpQ896FZt2IYR9gP6JkXz97FgRUQ+ExAuXlnZkWO7mfU3yVNDcO8m8tNzLmwI/u4=,iv:u1t204cGrAT2tlXJuueKuzHDYezc9CsZUBWlZS8z/eE=,tag:4soWzmcURxwlUdokOd0hMw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
