# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: github-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:SQaNaLeEJlE0eayupKiraRMRki61MnKDAgbafNCWJTw7ug3no0/AIw==,iv:CVVE/DmHekiknXi1dXZF0DCoqa40mX64rtmPybSjV80=,tag:dZKwuftSfnzKlIi0HsR45A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXa0I0T0x4V0hSTytaUWhh
            V2hzMEp5cHc3RzZjaStUYWNpNE5ISnFVdzJvCjc3R1VKWmtkSHdFMFRRNHE5eXNR
            V3NBd2JPVldsbnVCVDF1cE9EakkxY3cKLS0tIDRmNzAwYTVEdTFHNHRjZUtrRVFJ
            TzUzUlhZWTdBaUcyeEgwczJnOUVUeTQKIoA2uj95ew+pNh+Gmee8GID1KlWGP8Ne
            ZdB0hF/9y3qJiVz+Yvoh0VhR+paH5Qw4y6VHQmB8KMT39eaJ1rJZpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-09T08:47:29Z"
    mac: ENC[AES256_GCM,data:+um0u1OwNkCUO1XGHk+0Lmy8PVmocBVunwGM2SpH8i/YYUPlhu5N23Qymdh6k4NKIditrSac/+VUQ1NcP86115KkKvszdVzVUu3vjCn2HbPaOMBoxqnzWDWDMfvKb7u9iRxpaanFzNyQcDtAO0NjUi+AtTmM9QRx38Cr+si2VOM=,iv:pXrcNE9Ar+GYHt0KSP0u5kVktd+0uVkAsKK/06QwprQ=,tag:u6X8w+83DHR/8hJVs2FsQw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
