apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:nlHWtqGmgR6Ef5nD/4u+byvQpz7gxZ9kHv58jLWMljc=,iv:+SMTJFN0wXi85NNH3ILIWtZJCLWyftaaS9a9Oz0C/3M=,tag:7T9QU6mV/UAQPF09RDSZTg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qqz7ryljcrncf70a6n0yqptdq34nte99uj8j6ppucw94npccad0q304pkw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhVXliaGFJbklmRGJVVUlz
            eUl5cWhzdEloS0hrMmJmbVVHWldXaFA3SGkwCnd6WWlJa0M1NVkxUUVjVHByMXF6
            bXBIV2VEZlpqUHFCczRYUUZOUXM4MW8KLS0tIDdndk1pRyt4YlZIN3FXRXo5azJB
            MjI0dlE1R1NwUjNYRWQ5OHJSallNcEEK+HV87TqDKzfUVgpYM9FUh9r+kowcrwL5
            C/mVM0DunJC+GJ8ky9B6vgC4BpxqotU1L0EafEhexqf+Tt5Loj7sNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-04T14:08:19Z"
    mac: ENC[AES256_GCM,data:ef/eqN3KcpwUwQyejpEAeo28b1nU6IQ+HQcrkyqJg7tzThHy1/2SgVBnUEt8NsmNHPiAf8qIi825xdZDS0QMuh5cqwsPuoXYKPuOxiXuLvN/TrZNvOsRspr7cip+ooX6sfMzw60UGm0q997X6qYqXSeLT/ltcDiQbau8WcChzlY=,iv:tPjRPhWAV04R4JbkTqq0fO+5AFtbF4naa1aFltHaTk0=,tag:FJhaEbTF8wvaIYtLG/Qe3A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
