---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: mealie
  namespace: default
spec:
  interval: 10m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn: []
    # - name: rook-ceph-cluster
    #   namespace: rook-ceph
    # - name: volsync
    #   namespace: volsync
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/mealie-recipes/mealie
              tag: v1.0.0-RC1.1
            env:
              BASE_URL: https://mealie.${SECRET_DOMAIN}
              ALLOW_SIGNUP: false
              API_DOCS: false
              SMTP_HOST: ${SMTP_HOST_IP}
              SMTP_PORT: 25
              SMTP_AUTH_STRATEGY: NONE
              SMTP_FROM_EMAIL: mealie@${SECRET_DOMAIN}
            resources:
              requests:
                cpu: 100m
                memory: 500Mi
              limits:
                cpu: 200m
                memory: 800Mi
    service:
      main:
        ports:
          http:
            port: 9000
    ingress:
      main:
        enabled: true
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
          - host: &host "{{ .Release.Name }}-external.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
      internal:
        enabled: true
        className: internal
        hosts:
          - host: &host "{{ .Release.Name }}-internal.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        existingClaim: mealie-config
        globalMounts:
          - path: /app/data
