---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-config-dev-nfs
  namespace: dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: pve110-dynamic-nfs
