---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant-dev
  namespace: dev
spec:
  interval: 10m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: home-assistant
      version: 13.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    image:
      repository: homeassistant/home-assistant
      tag: 2022.6.1
    env:
      TZ: ${TIMEZONE}
    envFrom:
      - secretRef:
          name: home-assistant-secrets
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
    service:
      main:
        type: ClusterIP
        loadBalancerIP: ${HASS_DEV_IP}
        ports:
          http:
            port: 8123
    podAnnotations:
      secret.reloader.stakater.com/reload: "home-assistant"
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          nginx.org/websocket-services: home-assistant
          external-dns.alpha.kubernetes.io/target: ${SECRET_DOMAIN}
          cert-manager.io/cluster-issuer: letsencrypt-production
          hajimari.io/enable: "true"
          hajimari.io/icon: home-assistant
          ingress.kubernetes.io/whitelist-x-forwarded-for: "true"
        hosts:
          - host: hass.dev.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - hass.dev.${SECRET_DOMAIN}
            secretName: hass-dev-tls
    persistence:
      config:
        enabled: true
        existingClaim: home-assistant-config-dev
      backups:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "nfs1.${SECRET_PRIVATE_DOMAIN}"
            path: /volume1/k3sCluster/Apps/External/Backups/home_assistant
        mountPath: /config/backups
        accessMode: ReadWriteOnce
        size: 1M
    addons:
      codeserver:
        enabled: true
        image:
          repository: codercom/code-server
          tag: 4.4.0
        workingDir: /config
        args:
          - --auth
          - none
          - --user-data-dir
          - /config/.vscode
          - --extensions-dir
          - /config/.vscode
        env:
          HASS_SERVER: http://localhost:8123
          HASS_TOKEN: ${HASS_CONFIG_ACCESS_TOKEN}
        git:
          deployKeySecret: home-assistant-code-server
        ingress:
          enabled: true
          ingressClassName: "nginx"
          annotations:
            external-dns.alpha.kubernetes.io/target: ${SECRET_DOMAIN}
            cert-manager.io/cluster-issuer: letsencrypt-production
            hajimari.io/enable: "true"
            hajimari.io/icon: settings
            # nginx.ingress.kubernetes.io/auth-url: https://auth.${SECRET_DOMAIN}/oauth2/auth
            # nginx.ingress.kubernetes.io/auth-signin: https://auth.${SECRET_DOMAIN}/oauth2/start
          hosts:
            - host: &host hass-config.dev.${SECRET_DOMAIN}
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - hass-config.dev.${SECRET_DOMAIN}
              secretName: hass-dev-config-tls
        volumeMounts:
          - name: config
            mountPath: /config
          - name: backups
            mountPath: /config/hass-backups


    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        memory: 2Gi
