---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-dev-config-v1
  namespace: dev
  labels:
    k10.kasten.io/backup: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ceph-block
