# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:nJBeiT/d0qzLsDhu/OtJnX3bvLt4q8FPF3DejSsCUllUz8FYJs8OwQ==,iv:eHzu/VEB2yZji35U3ns6CqLWtNMwRgY3+zai3J8Gr6s=,tag:wuugvLPDpd7MvhwyvouA6g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMOENFZFNENVNvOUpHUW8w
            NDBsTSs4Ym1zTlNLMTdSdlRQZFhHTHZYMVU4CjNRMGppTW10MElNaEJSbGxIeFZX
            U2cvR0pHMWwyZHZBRElTbmxObURNVlEKLS0tIG9HUklVSHdFcGludGNqTSsySHQ3
            R01Ua2lvOHdMeElPdVlVSUNVNUFoeHcKBCokEHPrOs3vycyKuErD9MZyLWYrgdiF
            0y61hdpwg8RbBrLPQQ136MRQc7W2i8Hyet96HF+cN+vf1jjYiXqZJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-30T01:37:05Z"
    mac: ENC[AES256_GCM,data:TJMkhS9v91QHZTq6GM2Z1JdCLxN2M8cDUviLruaaMFEzE3Yvb2mimTz6HEp1wJ7AF8Ls+r41RG8Yf4yF5RPE1Z+v7K06LjNLEsVttmbqVY3Tn7dF2zkxHdkZQEsDJp4cALKvwdUBwQXzddC68EGUK6qnbVgDmGUS+CYVf3BU3AU=,iv:5XinodRrBzHRLO3cMiGxPo+eVbdRUprGslofoAEL/mM=,tag:e4C5Rlqz5uhcYAh1mjiw3g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
