# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:KI0mkNZyNRJ7D++jyXCml2RTUbca2sW7N3jaufBuwaXs9IQIQA==,iv:MhkhzRzY7E/jRA/jm9OLll4rUX+/VR1LFpDhEp3DrOA=,tag:XRdSGWz4t4QenwM1nVHLOQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4djdvYkNxUlc3TytPRkNR
            M3NmZVBLT1NndHdnRFpCamxZTXhMbTFXeFRRClpEVHZpZU03VVdYUXhmUVpoUTU3
            YktzQkRsendtL1d4Rk1abU9jNVFlNjgKLS0tIEJqa2dBU2F1OXdFNXRaOG9pWnN0
            Zjl3RG1BK1lLT2tpTjJxRWJzdE1lUEUKloWnfxcyUEEeRU7HAUnM+K76226oXVvK
            rinpG/gE7x9YBXKKqHyaeMfxpjYilBjtsy0W927tlbzXMsyqzNRbpw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-14T11:15:27Z"
    mac: ENC[AES256_GCM,data:M1ekS8fpDgnXOsdwKpVVEPjH4pAKsrKzMmSkvlSQLsFHCyc21tpYCyda+66qFpPrDypTCJwz9emqxuUu1aO9+e4L8P9lqfoFrTGyUhF3Sdp2r3RfWW2KVfqtlgVNFow0tkM5wvrF++rXjPyirH3AH5W5S4/hOThQo/Srnb6GhCQ=,iv:bLXHJQj0BB5yWGbKbEzAwSuI5fV6xHHf0YGQTsRwWw0=,tag:JM/AMfIS9/RS0Q6SngflgQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
