# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:nI+q8fkT/zmESBWQW0GKuAc7NVc1s9THqzwC2XQ8Q+UYB21C+A==,iv:hrwpUvIQ2dsJfq+7CaAqb41o0qe1U2ddSi80MpS/7zw=,tag:vW3tTVUw453oYXS2iITHDg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDeGc2ZnFiT1ZFcmI3RURm
            dldjZW02NHlpNUYxLzk4Y3ZqS09rSHhqR2xNClJrZzY5QldIZ1hEMVVhL01PUUF6
            NEhSMHU5d1FKTm9sWWhROGpyWEU1WlUKLS0tIFd5MkZtZGR3Q0o2dE5GdVYvalJu
            Mk1zdnVkQVZqeTdTVGZEQzBzeFQrT2MKHdwajwMY1WD5mmR28vRwH8HYNLlBhMp/
            t7vFObmPWd0Wn7Ot7gUtWxq1ZuYNt0jIvVnzXld58Pv2YL8g/YGQ7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-16T11:17:45Z"
    mac: ENC[AES256_GCM,data:KAfx59E/+mkKupKIoFGNXv976G+Nlm+18HFzLd/H+VT2mCQGG5ytMs/vxvc0BBw00jqMRKaOw5l+7mxFqGak6jzDN++VTsIkjcFGzWYVN+wOP2RWnI7uIg2XlyZ6SkfMF8q3nn1tLPhFWFB5d7CPT6gniaHBCfGGsvtK8WGMGJ8=,iv:5ueiQLxzAUGnUDtx49deseskptXY7OnRqQp0CXg4gkY=,tag:oxkom10yplCD3lwP43Q+hg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
