# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:xnAcOvwtpueYHQErMGIaw6zYzsE94/xr7gEIlqZkj27As376ew==,iv:te9CvOIYt2ZEjURGMwfxzyVqj1JdViV7QPTPiT+t5rE=,tag:b3gccaKc+VIZHCplJjxR0g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCbEZFaUMwY3FGTHVDRGxy
            UG1HZnRySmRtWkgybThNK3lQZUVlLzV3Mmt3CjRlNVphRjI0ZGxxNjhFc1YwRWJJ
            QlNhbXpONmhuVU53M1RXR0tUeHVmZm8KLS0tIFgzUks0ZHV1blRWKzFIR2dpSmo4
            Wk5zNW1tbFNMYWZsUzd6VEJrV0hnN1UK+Z5q4ZNQQFbZ5PY+vVgvC2y9Ddj9EjrL
            Yz3ozDGgkzuqq2fNdrINLWwuw0RL3ydQOeY3qrTwEGu/eztoT9xeCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-17T03:57:05Z"
    mac: ENC[AES256_GCM,data:dqMJLFr2OhmNrM+3grgUVwLx9/YeFGBUG6Fts4WDO6oEcZ5LLJR9MJvRIJfwHpMQrh2c9a6NWTo3G8X1mi0P9uM1mVt8PWQnWgD/PnBtPsCkIRu+mtNfGIdyvBxjDKsIKxhsJvQMgNPp8txvtsw08Tu1v5qV4G1J456Tgz+AxUk=,iv:1/mhvO/y7mIgpLdonKL7W2G0eyEwTV8sTBg47DIM1Bo=,tag:29zeSmWU0WjLlp2JZX0IrQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
