# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: rclone-conf
    namespace: kasten-io
stringData:
    rclone.conf: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmp488pwp74xx3ljg0gumh2nlz2ml3s4yxnner5094fr59pvdulqtgywe2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2NkV4aXpiTWJiM3g1STVN
            SlAwVkVOYzRxQlBrc29pc2dDQmhBT1U3UFhJCnVkTmNXdXNFY0h1QkdZUmxkL0ls
            cVl1cXZJZjIwbkNtZUFFYmM3eXNLNVkKLS0tIFJVUHcyMExPRlRIZ0ZUcHA3cWZk
            dnFwaVlaUTNnU21EN2NWNG8yNmlIdW8KukJ0e09kuiWw5nZVo/N9MmwJ2p5VNfP0
            z7xfteU/gnA1WAf9TnMlOYGMai5uZJEb26qOPbUlE3JCsg7ZZ4brPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-17T10:41:31Z"
    mac: ENC[AES256_GCM,data:d13Mqi4ja8ARR/3LfsjysC/FEO8XzmcORXXt8tdmTCfqTd3thnrtX9Bhgg5ZuCh6Z8pi/1ypTp5fnyEM9B43OxcGy01tBkP+zgKKwVD2PZpVXVard5mEKM/lzOeAZ/OOSlsWx4e3EtcuHOryUWsi3v92bWVqfSUrUXtQCWr/Byk=,iv:KtBM/YYeajZ4zysmqX1Y0YVQtmIhw/iULDS83BEctnk=,tag:bXzVAQENJNFyCbqu/95Dzw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
