apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:UFbQkFEsDBBdxkMjqWjXs6Hlzm2lx0lJRXqcyqeJGNlwp9g8OqyDuw==,iv:z95zM4UdMvw6BlqqLtYmItLgQEF5A1TJ0LHXe7JzbxM=,tag:kKjhCBMy2SU9ERQN9AANTA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qqz7ryljcrncf70a6n0yqptdq34nte99uj8j6ppucw94npccad0q304pkw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmS2M1WS9GTGtkYkFIbkU2
            R1BCbER3Q21wYzdUY2tkMTBTR1ZvM1FWU1cwCitjVkxZcEpkL1pFZDV2cytxZlFB
            QXJOZkJLRjFMNnRVN1BqVjFrYzZFejQKLS0tIGNZOUxBYytZQ2V6TUVCMFNwd2xs
            cW95UXp2VEEwS2VzdHBSTHpZcHBEdFkKc/6uuIyjAq5tcXLs4ICPTYD5L3XzHsm8
            YHdVe2oaPgPbl4GC9+Hd35rrM7tUCqW94aR1hlAE2R5i7DHZYK0UcA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-03T07:32:51Z"
    mac: ENC[AES256_GCM,data:mJ2XeGJ2fkR8uCzqUXKXBkGjG7CBHJcRU9L68J3tkKyU5eVHj7Z6mJbra/BAvnmS8ndo2LZ0WRe0WRFGLqAbsCChDDkxxpVkLR4k3lu++aKntvjlDZ3coxMs51EeoOOXdExWKpmhtCufXLilFjOiDFpolf9QTQpu1zr22nEAFTM=,iv:5mQCWPxNMzURzzRvtN+ztp3IFnqbGHVws8MxrTnl0pQ=,tag:Ld1RxH5hArrV9CLMoRJYlQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
