---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: home-assistant-internal
spec:
  endpoints:
    - dnsName: hass.${SECRET_DOMAIN}
      recordType: A
      targets: ["10.44.0.1"]
