---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-synology-downloads
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-synology-downloads
  resources:
    requests:
      storage: 1Mi
