---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-synology-photos
  namespace: media
spec:
  storageClassName: nfs-synology-photos
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: nfs1.${SECRET_PRIVATE_DOMAIN}
    path: "/volume1/photo"
