# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: bitwarden-cli-secret
stringData:
    BW_HOST: ENC[AES256_GCM,data:4H2LcEtmG0s7DJLOyOJDoHPIpj4l+aSf7RTg5fd2cGis5yE=,iv:Rl/xb6Jz4D+HIGoe4Q1PNDLF1enKy78mB0L4tg9QxDc=,tag:x2rRtMTieUQLSaBlThNxaA==,type:str]
    BW_USERNAME: ENC[AES256_GCM,data:Y4WLAZ5oG2NLU8OeSpGgKpIaSg==,iv:BDoTj+Q7TXAW5F3BnJz50MnQE+oLCJI2g41fZZukWDw=,tag:TQQn8lb+Nq5vbvXDn7GN3Q==,type:str]
    BW_PASSWORD: ENC[AES256_GCM,data:8gLOoV6k/w0=,iv:BOIlVM7hQ90YHd6BS+QCQ4nFwSXhcxtBlrUrE+I5XLQ=,tag:QTglFgvm41mDvOuhqRu1tg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qqz7ryljcrncf70a6n0yqptdq34nte99uj8j6ppucw94npccad0q304pkw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTZlFna1BWRytHQlZDQThi
            RTB3YVJKbXhMWUp1QnpvY2h5cG1rVFBYOVhrCkFPa1NoQnZGRmIrQkNJdTYwcjFV
            T2NSTmh2YXM1UlpnUmhXaFcvT3QxMk0KLS0tIGdaSUVWd3NGeERiTCtsQ3IzWjlk
            djFqOHBVd1dkeXVMczVPZkRtOCtGcTQKEsAZqlG9L1Z+p54GZSXqFS7JZB854jYK
            4Q8wEJSuU1+vz4CbAzfO31SQ38NdSi4sDfGWm0oqPJcNn68Xe6G6Xg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-12T09:53:54Z"
    mac: ENC[AES256_GCM,data:2lp9vsNMFMUnzAhXrz0Mz5PywINDBjxxZEax5z6RzvAuY50Pz6CGzMs27YcpOwzcPEP/f5H4rr/hg/Ekwnvxs23oE+/k8u0HVp7R5W+HUjrujLorB1ZVAO1zz9/+MVOMCrnSaCCXCBpZTs5udNkOWObmHXqw2FKQwTZIJNE7my8=,iv:b2ZPyPOnETbXC78Uogya6m0B0Ec2qkz5lqbai+jCgnM=,tag:RN09252uqJLeD2ybiqO6oA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
