# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: bwes-secret
stringData:
    BW_APPID: ENC[AES256_GCM,data:thCJeOZO+7KAlss=,iv:2xtR/95gjFhv9kK2gbT04KDSO2pmER7wnIjCGhedli8=,tag:gQH6NzsNxuNdA3JPskQUEA==,type:str]
    BW_CLIENTID: ENC[AES256_GCM,data:zvlqRupPGRgpH7M94wfIf+C1jimUiPNPqY5q92iRDVkXLw+7AdhD6uc=,iv:SldtdD2IZxShsfJ2i05FDSMjBtW8DOlL7c1LYyjVtvw=,tag:aC01zH1n2oTXH97JqqEYgQ==,type:str]
    BW_CLIENTSECRET: ENC[AES256_GCM,data:vjMX4ERnrrL3T7PUdYwGDsTw5fZt6DhwS4zW7FCk,iv:HY12Mxsg7o28SPUfY85/SMCIy8yRSZ//v11rXl6Y3JQ=,tag:D0IBSsvdk+MzigKcgKUB6A==,type:str]
    BW_HOST: ENC[AES256_GCM,data:uiSZUQs2moTYqgiTe0sOvIQ31C8InN5/0cRf7MwyOpmSPmw=,iv:sVKILgExj1gZB5eU71PGqOR0M8O4QMYiZeLFR9X4KbQ=,tag:w2BDub2wz7XVQTF/7qgJeA==,type:str]
    BW_PASSWORD: ENC[AES256_GCM,data:+XjmzncfcVVK,iv:B66gbas4DwC9/cfcqE/BSHTsu9tZXuhwjPuGe+X/zNY=,tag:BHUOET/RVQHPJmQgxcx2hQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qqz7ryljcrncf70a6n0yqptdq34nte99uj8j6ppucw94npccad0q304pkw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTZlFna1BWRytHQlZDQThi
            RTB3YVJKbXhMWUp1QnpvY2h5cG1rVFBYOVhrCkFPa1NoQnZGRmIrQkNJdTYwcjFV
            T2NSTmh2YXM1UlpnUmhXaFcvT3QxMk0KLS0tIGdaSUVWd3NGeERiTCtsQ3IzWjlk
            djFqOHBVd1dkeXVMczVPZkRtOCtGcTQKEsAZqlG9L1Z+p54GZSXqFS7JZB854jYK
            4Q8wEJSuU1+vz4CbAzfO31SQ38NdSi4sDfGWm0oqPJcNn68Xe6G6Xg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-15T11:41:53Z"
    mac: ENC[AES256_GCM,data:1QjpTzWdY/qUvcK+2Ez2kSd68NB0y8aF/YnJQmdV7aOGlx3IcQsD+Y4UGyeBK4NK6glgy28dygqZDbtYrHgyfwO2ecTpq5bde/6OfMeTJhABjk1nYclpeQFa9ZIYES1JUN18o5sKCs0rOYtzcTEz0XTK4NJ2mGdHWNMBMENYMbk=,iv:qKTKb+KqfEH4yndV3HP84c7WtxDzbcmX7oA+6ynbV+I=,tag:MM1V/toDbGJnQpUpJtzHGA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
