# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: bwes-secret
stringData:
    BW_APPID: ENC[AES256_GCM,data:u+P++KbLYNACiFxX,iv:N5IF63qYeCvhGNPu7OzPxaRLEceJXzLt9WYdwgjAp2g=,tag:xALY89WCjnk6czuQJFRM3g==,type:str]
    BW_CLIENTID: ENC[AES256_GCM,data:ztVDf1Em3Ty2d9z2dIlUXYTfzw==,iv:csmds6dqUOzkE5GNt2v3PWNTkcuNHt7rt1NMewrA20o=,tag:PSvI+8FjwtR907doSf9/Tg==,type:str]
    BW_CLIENTSECRET: ENC[AES256_GCM,data:0mth3panc9w=,iv:eiVLL3tqpX5OUzTcr0uGq2IY1SkILITbCiZeP1iY298=,tag:ho2e3+p5j3IE8KgEJX6hSw==,type:str]
    BW_HOST: ENC[AES256_GCM,data:4H2LcEtmG0s7DJLOyOJDoHPIpj4l+aSf7RTg5fd2cGis5yE=,iv:Rl/xb6Jz4D+HIGoe4Q1PNDLF1enKy78mB0L4tg9QxDc=,tag:x2rRtMTieUQLSaBlThNxaA==,type:str]
    BW_PASSWORD: ENC[AES256_GCM,data:t71u93YEwWo=,iv:mXbzUSm9EDTSYtOkzOK/rYN1FdC1/N55Mwwc5NUleqs=,tag:9YBkc2aeM4QXQChqYZSfuQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qqz7ryljcrncf70a6n0yqptdq34nte99uj8j6ppucw94npccad0q304pkw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTZlFna1BWRytHQlZDQThi
            RTB3YVJKbXhMWUp1QnpvY2h5cG1rVFBYOVhrCkFPa1NoQnZGRmIrQkNJdTYwcjFV
            T2NSTmh2YXM1UlpnUmhXaFcvT3QxMk0KLS0tIGdaSUVWd3NGeERiTCtsQ3IzWjlk
            djFqOHBVd1dkeXVMczVPZkRtOCtGcTQKEsAZqlG9L1Z+p54GZSXqFS7JZB854jYK
            4Q8wEJSuU1+vz4CbAzfO31SQ38NdSi4sDfGWm0oqPJcNn68Xe6G6Xg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-12T13:55:41Z"
    mac: ENC[AES256_GCM,data:Sj3hLQ9UdWX77/o3bKV+yojxyHrqGTQ2pX09YsRmKZMNCXpu50ND+andNv6chGDeZggGPY5yGGobnqygOUdOCvTc3XWBHng7QGX4gH0ZjJNS8b8G+t7Ug7y/OsqwtiYdKGi/QrvG7fZV18Na3C0GW2oP3wb346s0YSxQNIUwQrw=,iv:8pAKz4nXonM0/QCdKmPV6LttCDVPPQIQIa7SSxnOhSs=,tag:A4QrR5vIJLce1s47mZ/Tyw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
