---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
  namespace: rook-ceph
spec:
  interval: 2m
  chart:
    spec:
      # renovate: registryUrl=https://charts.rook.io/release
      chart: rook-ceph-cluster
      version: v1.9.3
      sourceRef:
        kind: HelmRepository
        name: rook-ceph-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  dependsOn:
    - name: rook-ceph
      namespace: rook-ceph
  values:
    monitoring:
      enabled: true
    ingress:
      dashboard:
        annotations:
          kubernetes.io/ingress.class: "nginx"
          hajimari.io/enable: "true"
          hajimari.io/icon: chess-rook
        host:
          name: &host "rook.${SECRET_DOMAIN}"
          path: "/"
        tls:
          - hosts:
              - *host
    cephClusterSpec:
      placement:
        all:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: role
                      operator: In
                      values:
                        - ceph-storage-node
      # The above placement information can also be specified for mon, osd, and mgr components
      #    mon:
      # Monitor deployments may contain an anti-affinity rule for avoiding monitor
      # collocation on the same node. This is a required rule when host network is used
      # or when AllowMultiplePerNode is false. Otherwise this anti-affinity rule is a
      # preferred rule with weight: 50.
      #    osd:
      #    mgr:
      #    cleanup:
      #
      resources:
        mon:
          requests:
            cpu: 35m
            memory: 800Mi
          limits:
            memory: 1024Mi
        osd:
          requests:
            cpu: "35m"
            memory: "1024Mi"
          limits:
            memory: "2048Mi"
      crashCollector:
        disable: false
      mgr:
        count: 1
        modules:
          # Several modules should not need to be included in this list. The "dashboard" and "monitoring" modules
          # are already enabled by other settings in the cluster CR.
          - name: pg_autoscaler
            enabled: true
      dashboard:
        enabled: true
        urlPrefix: /
        ssl: false
      storage:
        useAllNodes: false
        useAllDevices: false
        config:
          osdsPerDevice: "1"
        nodes:
          - name: "k3s-0"
            devices:
              - name: "sdb"
          - name: "k3s-a"
            devices:
              - name: "sdb"
          - name: "k3s-b"
            devices:
              - name: "sdb"
        healthCheck:
          daemonHealth:
            mon:
              disabled: false
              interval: 45s
            osd:
              disabled: false
              interval: 60s
            status:
              disabled: false
              interval: 60s
          # Change pod liveness probe timing or threshold values. Works for all mon,mgr,osd daemons.
          livenessProbe:
            mon:
              disabled: false
            mgr:
              disabled: false
            osd:
              disabled: false
          # Change pod startup probe timing or threshold values. Works for all mon,mgr,osd daemons.
          startupProbe:
            mon:
              disabled: false
            mgr:
              disabled: false
            osd:
              disabled: false
    cephBlockPoolsVolumeSnapshotClass:
      enabled: true
      name: csi-rbdplugin-snapclass
      annotations:
        k10.kasten.io/is-snapshot-class: "true"
    cephBlockPools:
      - name: ceph-blockpool
        spec:
          failureDomain: host
          replicated:
            size: 3
        storageClass:
          enabled: true
          name: ceph-block
          isDefault: true
          reclaimPolicy: Delete
          allowVolumeExpansion: true
          parameters:
            imageFormat: "2"
            imageFeatures: layering
            csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
            csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
            csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
            csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
            csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
            csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
            csi.storage.k8s.io/fstype: ext4
    cephFileSystems: []
    cephObjectStores: []
